import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { marketingLocales, type MarketingLocale } from "@/components/marketing/qdip-copy";
import { QdipSite } from "@/components/marketing/qdip-site";
const metadataByLocale:Record<MarketingLocale,{title:string;description:string}>={en:{title:"QDIP — Decision Engine for repeatable decisions",description:"Evaluate alternatives, constraints, risk and uncertainty. QDIP prepares an explainable recommendation; your team makes the final decision."},uk:{title:"QDIP — рушій прийняття рішень",description:"Оцінюйте альтернативи, обмеження, ризик і невизначеність. QDIP готує пояснювану рекомендацію, остаточне рішення приймає ваша команда."},pl:{title:"QDIP — silnik decyzyjny",description:"Oceniaj alternatywy, ograniczenia, ryzyko i niepewność. QDIP przygotowuje wyjaśnialną rekomendację; ostateczną decyzję podejmuje Twój zespół."}};
function isMarketingLocale(locale:string):locale is MarketingLocale{return marketingLocales.includes(locale as MarketingLocale)}
export function generateStaticParams(){return marketingLocales.map(locale=>({locale}))}
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const {locale}=await params;if(!isMarketingLocale(locale))return{};const v=metadataByLocale[locale];return{title:{absolute:v.title},description:v.description,alternates:{canonical:`https://qdip.ai/${locale}`,languages:{en:"https://qdip.ai/en",uk:"https://qdip.ai/uk",pl:"https://qdip.ai/pl"}},openGraph:{title:v.title,description:v.description,url:`https://qdip.ai/${locale}`,type:"website"}}}
export default async function LocalizedPlatformPage({params}:{params:Promise<{locale:string}>}){const {locale}=await params;if(!isMarketingLocale(locale))notFound();return <QdipSite locale={locale}/>}
