import type { StudioLocale } from './studio-locale'

export const STUDIO_COPY = {
  en: {
    language: { label: 'Language', switchTo: 'Switch language to' },
    headerStatus: {
      checking: { full: 'Core checking', compact: 'Checking' },
      connected: { full: 'Core connected', compact: 'Connected' },
      unavailable: { full: 'Core unavailable', compact: 'Offline' },
    },
    nav: {
      decisions: 'Decisions',
      decisionsDescription: 'Alternatives, evaluation, constraints, validation and runs',
      evidenceSources: 'Evidence Sources',
      evidenceSourcesDescription: 'Domain capabilities and evidence providers',
      evidenceMapping: 'Evidence Mapping',
      evidenceMappingDescription: 'Map evidence outputs into the decision model',
      evaluationContracts: 'Evaluation Contracts',
      evaluationContractsDescription: 'Reusable platform evaluation contracts',
      decisionWorkspace: 'DECISION WORKSPACE',
      advancedPlatform: 'ADVANCED · PLATFORM',
      openObservatory: 'Open Observatory',
      workspace: 'Workspace',
    },
    breadcrumbs: { label: 'Breadcrumb', home: 'QDIP home', studio: 'Decision Studio', advanced: 'Advanced' },
    decisionStudio: {
      titles: {
        profiles: 'Decision Workspace',
        plugins: 'Evidence Sources',
        dimensions: 'Evaluation Contracts',
        bindings: 'Evidence Mapping',
      },
      descriptions: {
        profiles:
          'Model a decision from alternatives through evaluation, evidence and constraints, then validate and run it.',
        plugins: 'Advanced: inspect the domain capabilities that supply evidence and decision inputs.',
        dimensions: 'Advanced: inspect reusable evaluation contracts and evaluator schemas.',
        bindings: 'Advanced: map evidence-source outputs into the evaluation model.',
      },
      retry: 'Retry',
      loading: 'Loading Decision Studio…',
      enabled: 'Enabled',
      disabled: 'Disabled',
      version: 'Version',
      category: 'Category',
      general: 'General',
      capabilities: 'Capabilities',
      outputs: 'Outputs',
      technicalDetails: 'Technical details',
      availableOutputs: 'Available outputs',
      noOutputs: 'No dimension outputs declared.',
      type: 'Type',
      phase: 'Phase',
      unavailable: 'Unavailable',
      source: 'Source',
      blocking: 'Blocking',
      yes: 'Yes',
      no: 'No',
      evaluatorSchemas: 'Evaluator and schemas',
      evaluator: 'Evaluator',
      configurationSchema: 'Configuration schema',
      valueSchema: 'Value schema',
      evidenceSource: 'Evidence source',
      selectEvidenceSource: 'Select an evidence source',
      backToDecisions: 'Back to decisions',
      decisionWorkflow: 'Decision workflow',
      decision: 'Decision',
      untitledDecision: 'Untitled decision',
      mode: 'Mode',
      editing: 'Editing',
      newModel: 'New model',
      validation: 'Validation',
      continuous: 'Continuous',
      workflowHelp:
        'Define alternatives, evaluation criteria, evidence and constraints. Validate the model before running it; platform contracts stay in Advanced configuration.',
      deleted: 'Decision model deleted. Historical decisions are retained.',
      savedAtVersion: 'saved at version',
    },
    dashboard: {
      aria: 'Decision profiles workspace',
      createProfile: 'Create profile',
      importJson: 'Import profile JSON',
      invalidJson: 'Select a DecisionProfile JSON file.',
      search: 'Search profiles',
      searchPlaceholder: 'Search profiles…',
      filter: 'Filter profiles by status',
      allStatuses: 'All statuses',
      active: 'Active',
      draft: 'Draft',
      invalid: 'Invalid',
      noProfiles: 'No profiles yet',
      noProfilesHelp: 'Create a profile or import an example to configure alternatives, dimensions and rules.',
      createFirst: 'Create first profile',
      decisionProfiles: 'Decision Profiles',
      name: 'Name',
      domain: 'Domain',
      version: 'Version',
      status: 'Status',
      alternatives: 'Alternatives',
      dimensions: 'Dimensions',
      inspect: 'Inspect',
      noMatches: 'No profiles match the current search and status filter.',
      overview: 'Profile overview',
      boundInputs: 'Bound inputs',
      warnings: 'Warnings',
      validationAttention: 'Validation requires attention',
      openProfile: 'Open profile',
      evaluate: 'Evaluate',
      deleteProfile: 'Delete profile',
      confirmDelete: 'Confirm delete',
      cancel: 'Cancel',
      statusActive: 'ACTIVE',
      statusDraft: 'DRAFT',
      statusInvalid: 'INVALID',
    },
    detail: {
      retry: 'Retry',
      loading: 'Loading profile…',
      decisionProfiles: 'Decision Profiles',
      version: 'Version',
      active: 'Active',
      draft: 'Draft',
      profileSections: 'Profile sections',
      overview: 'Overview',
      alternatives: 'Alternatives',
      dimensions: 'Dimensions',
      constraints: 'Constraints',
      policies: 'Policies',
      compliance: 'Compliance',
      profile: 'Profile',
      status: 'Status',
      plugin: 'Plugin',
      capability: 'Capability',
      executionModel: 'Execution model',
      outputBindings: 'Output Bindings',
      decisionDimensions: 'Decision Dimensions',
      decision: 'Decision',
      evaluate: 'Evaluate',
      enabledDimensions: 'Enabled dimensions',
      dimension: 'Dimension',
      source: 'Source',
      weight: 'Weight',
      required: 'Required',
      yes: 'Yes',
      no: 'No',
      constraintsHelp: 'Rules for this profile determine whether each alternative is feasible. Blocking: Yes.',
      policiesHelp: 'Policies may require actions or approvals without necessarily making an alternative infeasible.',
      complianceHelp:
        'Frameworks and rules for this profile, including conditions, actions and severity. A framework such as GDPR is a ruleset, not a numeric score.',
      context: 'Decision model context',
      section: 'Section',
      validation: 'Validation',
      contextHelp:
        'This inspector stays secondary to the model canvas. Constraints, dimensions, policies and evidence bindings remain parts of one decision system rather than separate CRUD screens.',
      savedAtVersion: 'saved at version',
      businessConfigured: 'Business configured',
      dipCalculated: 'DIP calculated',
      pluginSupplied: 'Plugin supplied',
      runtimeSupplied: 'Runtime supplied',
    },
    editor: {
      editProfile: 'Edit profile',
      createProfile: 'Create profile',
      active: 'Active',
      draft: 'Draft',
      profileId: 'Profile ID',
      name: 'Name',
      newVersion: 'New version',
      version: 'Version',
      preserveVersion: 'Use a new version to preserve previous configuration.',
      plugin: 'Plugin',
      selectPlugin: 'Select plugin',
      disabled: 'disabled',
      capability: 'Capability',
      unversioned: 'unversioned',
      pinnedContracts: 'Pinned contracts',
      unavailable: 'unavailable',
      useInstalledVersions: 'Use installed contract versions',
      activateAfterValidation: 'Activate after validation',
      alternatives: 'Alternatives',
      alternativesHelp: 'Describe the options and their attributes. Dimensions evaluate each option separately.',
      alternativeId: 'Alternative ID',
      label: 'Label',
      attributes: 'Attributes',
      removeAlternative: 'Remove alternative',
      addAlternative: 'Add alternative',
      decisionDimensions: 'Decision dimensions',
      dimensionsHelp: 'Select relevant dimensions, pin their contracts, and configure evaluation.',
      contractUnavailable: 'This pinned dimension contract is unavailable.',
      contractVersion: 'Contract version',
      weight: 'Weight',
      pluginBinding: 'Plugin output binding',
      configurationRuntime: 'Configuration / runtime input',
      required: 'Required',
      runtimeSchema: 'Runtime context schema',
      runtimeSchemaHelp:
        'Validate application-supplied context separately from business configuration and plugin inputs.',
      saving: 'Saving…',
      saveProfile: 'Save profile',
    },
    bindings: {
      loading: 'Loading bindings…',
      saved: 'Bindings saved. Update profiles to reference changed binding versions.',
      intro: 'Map declared outputs to dimension inputs. Change a binding’s version when editing its contract.',
      pinnedContracts: 'Pinned contracts',
      useInstalledVersions: 'Use installed contract versions',
      bindingId: 'Binding ID',
      version: 'Version',
      availableOutput: 'Available output',
      dimensionVersion: 'Dimension version',
      unavailable: 'unavailable',
      requiredOutput: 'Required output',
      enabled: 'Enabled',
      advancedDetails: 'Advanced details',
      internalSourcePath: 'Internal source path',
      targetPath: 'Target field → relative source path (or null)',
      removeBinding: 'Remove binding',
      addBinding: 'Add binding',
      saving: 'Saving…',
      saveBindings: 'Save bindings',
      noOutputs: 'This plugin has no declared dimension outputs.',
    },
    runner: {
      evaluate: 'Evaluate',
      description: 'Supply context for this execution. The result will be recorded in Observatory.',
      runtimeContext: 'Runtime decision context',
      pluginInput: 'Plugin capability input',
      evaluating: 'Evaluating…',
      evaluateAlternatives: 'Evaluate alternatives',
      noAlternative: 'No feasible alternative',
      inspect: 'Inspect decision and audit',
    },
    genericPanel: {
      loading: 'Loading application view…',
      alternative: 'Alternative',
      feasible: 'Feasible',
      score: 'Score',
      rank: 'Rank',
      requiredActions: 'Required actions',
      yes: 'Yes',
      no: 'No',
    },
    schema: {
      invalidJson: 'Enter valid JSON before saving.',
      configuration: 'Configuration',
      removeItem: 'Remove item',
      addItem: 'Add item',
    },
    shell: {
      motto: 'Model · connect · validate',
    },
    presentation: {
      sections: {
        overview: 'Overview',
        alternatives: 'Alternatives',
        dimensions: 'Dimensions',
        constraints: 'Constraints',
        policies: 'Policies',
        compliance: 'Compliance',
      },
      businessConfigured: 'Business configured',
      dipCalculated: 'DIP calculated',
      pluginSupplied: 'Plugin supplied',
      runtimeSupplied: 'Runtime supplied',
      rule: 'Rule',
      framework: 'Framework',
      action: 'Action',
      severity: 'Severity',
      budgetConstraint: 'Budget constraint',
      budgetHelp: 'Calculated cost must stay within the configured budget.',
    },
  },
  uk: {
    language: { label: 'Мова', switchTo: 'Перемкнути мову на' },
    headerStatus: {
      checking: { full: 'Core перевіряється', compact: 'Перевірка' },
      connected: { full: 'Core підключено', compact: 'Підключено' },
      unavailable: { full: 'Core недоступний', compact: 'Недоступно' },
    },
    nav: {
      decisions: 'Рішення',
      decisionsDescription: 'Альтернативи, оцінювання, обмеження, валідація та запуски',
      evidenceSources: 'Джерела доказів',
      evidenceSourcesDescription: 'Доменні можливості та провайдери доказів',
      evidenceMapping: 'Мапінг доказів',
      evidenceMappingDescription: 'Мапінг виходів джерел доказів у модель рішення',
      evaluationContracts: 'Контракти оцінювання',
      evaluationContractsDescription: 'Повторно використовувані контракти оцінювання платформи',
      decisionWorkspace: 'РОБОЧИЙ ПРОСТІР РІШЕНЬ',
      advancedPlatform: 'РОЗШИРЕНЕ · ПЛАТФОРМА',
      openObservatory: 'Відкрити Observatory',
      workspace: 'Робочий простір',
    },
    breadcrumbs: {
      label: 'Навігаційний ланцюжок',
      home: 'Головна QDIP',
      studio: 'Decision Studio',
      advanced: 'Розширене',
    },
    decisionStudio: {
      titles: {
        profiles: 'Робочий простір рішень',
        plugins: 'Джерела доказів',
        dimensions: 'Контракти оцінювання',
        bindings: 'Мапінг доказів',
      },
      descriptions: {
        profiles:
          'Змоделюйте рішення від альтернатив через оцінювання, докази й обмеження, а потім валідуйте та запустіть його.',
        plugins: 'Розширене: перегляд доменних можливостей, які постачають докази й вхідні дані рішення.',
        dimensions: 'Розширене: перегляд повторно використовуваних контрактів оцінювання та схем модулів оцінювання.',
        bindings: 'Розширене: мапінг виходів джерел доказів у модель оцінювання.',
      },
      retry: 'Повторити',
      loading: 'Завантаження Decision Studio…',
      enabled: 'Увімкнено',
      disabled: 'Вимкнено',
      version: 'Версія',
      category: 'Категорія',
      general: 'Загальна',
      capabilities: 'Можливості',
      outputs: 'Виходи',
      technicalDetails: 'Технічні деталі',
      availableOutputs: 'Доступні виходи',
      noOutputs: 'Виходи критерію не оголошені.',
      type: 'Тип',
      phase: 'Фаза',
      unavailable: 'Недоступно',
      source: 'Джерело',
      blocking: 'Блокувальне',
      yes: 'Так',
      no: 'Ні',
      evaluatorSchemas: 'Модуль оцінювання і схеми',
      evaluator: 'Модуль оцінювання',
      configurationSchema: 'Схема конфігурації',
      valueSchema: 'Схема значення',
      evidenceSource: 'Джерело доказів',
      selectEvidenceSource: 'Оберіть джерело доказів',
      backToDecisions: 'Назад до рішень',
      decisionWorkflow: 'Процес рішення',
      decision: 'Рішення',
      untitledDecision: 'Рішення без назви',
      mode: 'Режим',
      editing: 'Редагування',
      newModel: 'Нова модель',
      validation: 'Валідація',
      continuous: 'Безперервна',
      workflowHelp:
        'Визначте альтернативи, критерії оцінювання, докази та обмеження. Валідуйте модель перед запуском; контракти платформи залишаються у розширеній конфігурації.',
      deleted: 'Модель рішення видалено. Історичні рішення збережено.',
      savedAtVersion: 'збережено у версії',
    },
    dashboard: {
      aria: 'Робочий простір профілів рішень',
      createProfile: 'Створити профіль',
      importJson: 'Імпортувати JSON профілю',
      invalidJson: 'Оберіть файл DecisionProfile JSON.',
      search: 'Пошук профілів',
      searchPlaceholder: 'Пошук профілів…',
      filter: 'Фільтр профілів за статусом',
      allStatuses: 'Усі статуси',
      active: 'Активний',
      draft: 'Чернетка',
      invalid: 'Некоректний',
      noProfiles: 'Профілів ще немає',
      noProfilesHelp: 'Створіть профіль або імпортуйте приклад, щоб налаштувати альтернативи, критерії та правила.',
      createFirst: 'Створити перший профіль',
      decisionProfiles: 'Профілі рішень',
      name: 'Назва',
      domain: 'Домен',
      version: 'Версія',
      status: 'Статус',
      alternatives: 'Альтернативи',
      dimensions: 'Критерії',
      inspect: 'Переглянути',
      noMatches: 'Жоден профіль не відповідає поточному пошуку та фільтру статусу.',
      overview: 'Огляд профілю',
      boundInputs: 'Зв’язані входи',
      warnings: 'Попередження',
      validationAttention: 'Валідація потребує уваги',
      openProfile: 'Відкрити профіль',
      evaluate: 'Оцінити',
      deleteProfile: 'Видалити профіль',
      confirmDelete: 'Підтвердити видалення',
      cancel: 'Скасувати',
      statusActive: 'АКТИВНИЙ',
      statusDraft: 'ЧЕРНЕТКА',
      statusInvalid: 'НЕКОРЕКТНИЙ',
    },
    detail: {
      retry: 'Повторити',
      loading: 'Завантаження профілю…',
      decisionProfiles: 'Профілі рішень',
      version: 'Версія',
      active: 'Активний',
      draft: 'Чернетка',
      profileSections: 'Розділи профілю',
      overview: 'Огляд',
      alternatives: 'Альтернативи',
      dimensions: 'Критерії',
      constraints: 'Обмеження',
      policies: 'Політики',
      compliance: 'Відповідність',
      profile: 'Профіль',
      status: 'Статус',
      plugin: 'Плагін',
      capability: 'Можливість',
      executionModel: 'Модель виконання',
      outputBindings: 'Зв’язки виходів',
      decisionDimensions: 'Критерії рішення',
      decision: 'Рішення',
      evaluate: 'Оцінити',
      enabledDimensions: 'Увімкнені критерії',
      dimension: 'Критерій',
      source: 'Джерело',
      weight: 'Вага',
      required: 'Обов’язкове',
      yes: 'Так',
      no: 'Ні',
      constraintsHelp: 'Правила цього профілю визначають, чи є кожна альтернатива допустимою. Блокування: так.',
      policiesHelp: 'Політики можуть вимагати дій або погоджень, не обов’язково роблячи альтернативу недопустимою.',
      complianceHelp:
        'Набори правил і правила профілю, включно з умовами, діями й серйозністю. Набір правил на кшталт GDPR не є числовою оцінкою.',
      context: 'Контекст моделі рішення',
      section: 'Розділ',
      validation: 'Валідація',
      contextHelp:
        'Цей інспектор залишається другорядним щодо полотна моделі. Обмеження, критерії, політики та зв’язки доказів є частинами однієї системи рішень, а не окремими екранами керування.',
      savedAtVersion: 'збережено у версії',
      businessConfigured: 'Налаштовано бізнесом',
      dipCalculated: 'Обчислено DIP',
      pluginSupplied: 'Надано плагіном',
      runtimeSupplied: 'Надано під час виконання',
    },
    editor: {
      editProfile: 'Редагувати профіль',
      createProfile: 'Створити профіль',
      active: 'Активний',
      draft: 'Чернетка',
      profileId: 'ID профілю',
      name: 'Назва',
      newVersion: 'Нова версія',
      version: 'Версія',
      preserveVersion: 'Використайте нову версію, щоб зберегти попередню конфігурацію.',
      plugin: 'Плагін',
      selectPlugin: 'Оберіть плагін',
      disabled: 'вимкнено',
      capability: 'Можливість',
      unversioned: 'без версії',
      pinnedContracts: 'Закріплені контракти',
      unavailable: 'недоступно',
      useInstalledVersions: 'Використати встановлені версії контрактів',
      activateAfterValidation: 'Активувати після валідації',
      alternatives: 'Альтернативи',
      alternativesHelp: 'Опишіть варіанти та їхні атрибути. Критерії оцінюють кожен варіант окремо.',
      alternativeId: 'ID альтернативи',
      label: 'Мітка',
      attributes: 'Атрибути',
      removeAlternative: 'Видалити альтернативу',
      addAlternative: 'Додати альтернативу',
      decisionDimensions: 'Критерії рішення',
      dimensionsHelp: 'Оберіть релевантні критерії, закріпіть їхні контракти та налаштуйте оцінювання.',
      contractUnavailable: 'Цей закріплений контракт критерію недоступний.',
      contractVersion: 'Версія контракту',
      weight: 'Вага',
      pluginBinding: 'Зв’язок виходу плагіна',
      configurationRuntime: 'Конфігурація / вхід під час виконання',
      required: 'Обов’язкове',
      runtimeSchema: 'Схема контексту виконання',
      runtimeSchemaHelp:
        'Валідуйте контекст, що надходить від застосунку, окремо від бізнес-конфігурації та входів плагіна.',
      saving: 'Збереження…',
      saveProfile: 'Зберегти профіль',
    },
    bindings: {
      loading: 'Завантаження зв’язків…',
      saved: 'Зв’язки збережено. Оновіть профілі, щоб вони посилалися на змінені версії зв’язків.',
      intro:
        'Зіставте оголошені виходи з входами критеріїв. Змінюйте версію зв’язку під час редагування його контракту.',
      pinnedContracts: 'Закріплені контракти',
      useInstalledVersions: 'Використати встановлені версії контрактів',
      bindingId: 'ID зв’язку',
      version: 'Версія',
      availableOutput: 'Доступний вихід',
      dimensionVersion: 'Версія критерію',
      unavailable: 'недоступно',
      requiredOutput: 'Обов’язковий вихід',
      enabled: 'Увімкнено',
      advancedDetails: 'Розширені деталі',
      internalSourcePath: 'Внутрішній шлях джерела',
      targetPath: 'Цільове поле → відносний шлях джерела (або null)',
      removeBinding: 'Видалити зв’язок',
      addBinding: 'Додати зв’язок',
      saving: 'Збереження…',
      saveBindings: 'Зберегти зв’язки',
      noOutputs: 'Цей плагін не має оголошених виходів критеріїв.',
    },
    runner: {
      evaluate: 'Оцінити',
      description: 'Надайте контекст для цього запуску. Результат буде записано в Observatory.',
      runtimeContext: 'Контекст рішення під час виконання',
      pluginInput: 'Вхід можливості плагіна',
      evaluating: 'Оцінювання…',
      evaluateAlternatives: 'Оцінити альтернативи',
      noAlternative: 'Немає допустимої альтернативи',
      inspect: 'Переглянути рішення та аудит',
    },
    genericPanel: {
      loading: 'Завантаження представлення застосунку…',
      alternative: 'Альтернатива',
      feasible: 'Допустима',
      score: 'Оцінка',
      rank: 'Ранг',
      requiredActions: 'Обов’язкові дії',
      yes: 'Так',
      no: 'Ні',
    },
    schema: {
      invalidJson: 'Введіть коректний JSON перед збереженням.',
      configuration: 'Конфігурація',
      removeItem: 'Видалити елемент',
      addItem: 'Додати елемент',
    },
    shell: {
      motto: 'Моделюй · підключай · валідуй',
    },
    presentation: {
      sections: {
        overview: 'Огляд',
        alternatives: 'Альтернативи',
        dimensions: 'Критерії',
        constraints: 'Обмеження',
        policies: 'Політики',
        compliance: 'Відповідність',
      },
      businessConfigured: 'Налаштовано бізнесом',
      dipCalculated: 'Обчислено DIP',
      pluginSupplied: 'Надано плагіном',
      runtimeSupplied: 'Надано під час виконання',
      rule: 'Правило',
      framework: 'Набір правил',
      action: 'Дія',
      severity: 'Серйозність',
      budgetConstraint: 'Бюджетне обмеження',
      budgetHelp: 'Розрахована вартість має залишатися в межах налаштованого бюджету.',
    },
  },
  pl: {
    language: { label: 'Język', switchTo: 'Zmień język na' },
    headerStatus: {
      checking: { full: 'Core: sprawdzanie', compact: 'Sprawdzanie' },
      connected: { full: 'Core połączony', compact: 'Połączono' },
      unavailable: { full: 'Core niedostępny', compact: 'Niedostępny' },
    },
    nav: {
      decisions: 'Decyzje',
      decisionsDescription: 'Alternatywy, ocena, ograniczenia, walidacja i uruchomienia',
      evidenceSources: 'Źródła dowodów',
      evidenceSourcesDescription: 'Możliwości domenowe i dostawcy dowodów',
      evidenceMapping: 'Mapowanie dowodów',
      evidenceMappingDescription: 'Mapuj wyniki źródeł dowodów do modelu decyzji',
      evaluationContracts: 'Kontrakty oceny',
      evaluationContractsDescription: 'Wielokrotnego użytku kontrakty oceny platformy',
      decisionWorkspace: 'PRZESTRZEŃ DECYZJI',
      advancedPlatform: 'ZAAWANSOWANE · PLATFORMA',
      openObservatory: 'Otwórz Observatory',
      workspace: 'Przestrzeń robocza',
    },
    breadcrumbs: {
      label: 'Ścieżka nawigacji',
      home: 'Strona główna QDIP',
      studio: 'Decision Studio',
      advanced: 'Zaawansowane',
    },
    decisionStudio: {
      titles: {
        profiles: 'Przestrzeń decyzji',
        plugins: 'Źródła dowodów',
        dimensions: 'Kontrakty oceny',
        bindings: 'Mapowanie dowodów',
      },
      descriptions: {
        profiles:
          'Modeluj decyzję od alternatyw przez ocenę, dowody i ograniczenia, a następnie zweryfikuj i uruchom model.',
        plugins: 'Zaawansowane: przeglądaj możliwości domenowe dostarczające dowody i dane wejściowe decyzji.',
        dimensions: 'Zaawansowane: przeglądaj kontrakty oceny wielokrotnego użytku oraz schematy modułów oceny.',
        bindings: 'Zaawansowane: mapuj wyniki źródeł dowodów do modelu oceny.',
      },
      retry: 'Ponów',
      loading: 'Ładowanie Decision Studio…',
      enabled: 'Włączone',
      disabled: 'Wyłączone',
      version: 'Wersja',
      category: 'Kategoria',
      general: 'Ogólne',
      capabilities: 'Możliwości',
      outputs: 'Wyniki',
      technicalDetails: 'Szczegóły techniczne',
      availableOutputs: 'Dostępne wyniki',
      noOutputs: 'Nie zadeklarowano wyników kryterium.',
      type: 'Typ',
      phase: 'Faza',
      unavailable: 'Niedostępne',
      source: 'Źródło',
      blocking: 'Blokujące',
      yes: 'Tak',
      no: 'Nie',
      evaluatorSchemas: 'Moduł oceny i schematy',
      evaluator: 'Moduł oceny',
      configurationSchema: 'Schemat konfiguracji',
      valueSchema: 'Schemat wartości',
      evidenceSource: 'Źródło dowodów',
      selectEvidenceSource: 'Wybierz źródło dowodów',
      backToDecisions: 'Wróć do decyzji',
      decisionWorkflow: 'Przepływ decyzji',
      decision: 'Decyzja',
      untitledDecision: 'Decyzja bez nazwy',
      mode: 'Tryb',
      editing: 'Edycja',
      newModel: 'Nowy model',
      validation: 'Walidacja',
      continuous: 'Ciągła',
      workflowHelp:
        'Zdefiniuj alternatywy, kryteria oceny, dowody i ograniczenia. Zweryfikuj model przed uruchomieniem; kontrakty platformy pozostają w konfiguracji zaawansowanej.',
      deleted: 'Model decyzji usunięto. Historyczne decyzje zostały zachowane.',
      savedAtVersion: 'zapisano w wersji',
    },
    dashboard: {
      aria: 'Przestrzeń profili decyzji',
      createProfile: 'Utwórz profil',
      importJson: 'Importuj JSON profilu',
      invalidJson: 'Wybierz plik DecisionProfile JSON.',
      search: 'Szukaj profili',
      searchPlaceholder: 'Szukaj profili…',
      filter: 'Filtruj profile według statusu',
      allStatuses: 'Wszystkie statusy',
      active: 'Aktywny',
      draft: 'Szkic',
      invalid: 'Nieprawidłowy',
      noProfiles: 'Brak profili',
      noProfilesHelp: 'Utwórz profil lub zaimportuj przykład, aby skonfigurować alternatywy, kryteria i reguły.',
      createFirst: 'Utwórz pierwszy profil',
      decisionProfiles: 'Profile decyzji',
      name: 'Nazwa',
      domain: 'Domena',
      version: 'Wersja',
      status: 'Status',
      alternatives: 'Alternatywy',
      dimensions: 'Kryteria',
      inspect: 'Sprawdź',
      noMatches: 'Żaden profil nie pasuje do bieżącego wyszukiwania i filtra statusu.',
      overview: 'Przegląd profilu',
      boundInputs: 'Powiązane wejścia',
      warnings: 'Ostrzeżenia',
      validationAttention: 'Walidacja wymaga uwagi',
      openProfile: 'Otwórz profil',
      evaluate: 'Oceń',
      deleteProfile: 'Usuń profil',
      confirmDelete: 'Potwierdź usunięcie',
      cancel: 'Anuluj',
      statusActive: 'AKTYWNY',
      statusDraft: 'SZKIC',
      statusInvalid: 'NIEPRAWIDŁOWY',
    },
    detail: {
      retry: 'Ponów',
      loading: 'Ładowanie profilu…',
      decisionProfiles: 'Profile decyzji',
      version: 'Wersja',
      active: 'Aktywny',
      draft: 'Szkic',
      profileSections: 'Sekcje profilu',
      overview: 'Przegląd',
      alternatives: 'Alternatywy',
      dimensions: 'Kryteria',
      constraints: 'Ograniczenia',
      policies: 'Polityki',
      compliance: 'Zgodność',
      profile: 'Profil',
      status: 'Status',
      plugin: 'Wtyczka',
      capability: 'Możliwość',
      executionModel: 'Model wykonania',
      outputBindings: 'Powiązania wyników',
      decisionDimensions: 'Kryteria decyzji',
      decision: 'Decyzja',
      evaluate: 'Oceń',
      enabledDimensions: 'Włączone kryteria',
      dimension: 'Kryterium',
      source: 'Źródło',
      weight: 'Waga',
      required: 'Wymagane',
      yes: 'Tak',
      no: 'Nie',
      constraintsHelp: 'Reguły tego profilu określają, czy każda alternatywa jest wykonalna. Blokowanie: tak.',
      policiesHelp:
        'Polityki mogą wymagać działań lub zatwierdzeń bez konieczności uznania alternatywy za niewykonalną.',
      complianceHelp:
        'Zestawy reguł i reguły profilu, w tym warunki, działania i poziom istotności. Zestaw reguł taki jak GDPR nie jest wynikiem liczbowym.',
      context: 'Kontekst modelu decyzji',
      section: 'Sekcja',
      validation: 'Walidacja',
      contextHelp:
        'Inspektor pozostaje drugorzędny wobec modelu. Ograniczenia, kryteria, polityki i powiązania dowodów są elementami jednego systemu decyzji, a nie oddzielnymi ekranami zarządzania.',
      savedAtVersion: 'zapisano w wersji',
      businessConfigured: 'Skonfigurowane biznesowo',
      dipCalculated: 'Obliczone przez DIP',
      pluginSupplied: 'Dostarczone przez wtyczkę',
      runtimeSupplied: 'Dostarczone w czasie wykonania',
    },
    editor: {
      editProfile: 'Edytuj profil',
      createProfile: 'Utwórz profil',
      active: 'Aktywny',
      draft: 'Szkic',
      profileId: 'ID profilu',
      name: 'Nazwa',
      newVersion: 'Nowa wersja',
      version: 'Wersja',
      preserveVersion: 'Użyj nowej wersji, aby zachować poprzednią konfigurację.',
      plugin: 'Wtyczka',
      selectPlugin: 'Wybierz wtyczkę',
      disabled: 'wyłączony',
      capability: 'Możliwość',
      unversioned: 'bez wersji',
      pinnedContracts: 'Przypięte kontrakty',
      unavailable: 'niedostępne',
      useInstalledVersions: 'Użyj zainstalowanych wersji kontraktów',
      activateAfterValidation: 'Aktywuj po walidacji',
      alternatives: 'Alternatywy',
      alternativesHelp: 'Opisz opcje i ich atrybuty. Kryteria oceniają każdą opcję oddzielnie.',
      alternativeId: 'ID alternatywy',
      label: 'Etykieta',
      attributes: 'Atrybuty',
      removeAlternative: 'Usuń alternatywę',
      addAlternative: 'Dodaj alternatywę',
      decisionDimensions: 'Kryteria decyzji',
      dimensionsHelp: 'Wybierz odpowiednie kryteria, przypnij ich kontrakty i skonfiguruj ocenę.',
      contractUnavailable: 'Ten przypięty kontrakt kryterium jest niedostępny.',
      contractVersion: 'Wersja kontraktu',
      weight: 'Waga',
      pluginBinding: 'Powiązanie wyniku wtyczki',
      configurationRuntime: 'Konfiguracja / wejście w czasie wykonania',
      required: 'Wymagane',
      runtimeSchema: 'Schemat kontekstu wykonania',
      runtimeSchemaHelp:
        'Waliduj kontekst dostarczony przez aplikację oddzielnie od konfiguracji biznesowej i wejść wtyczki.',
      saving: 'Zapisywanie…',
      saveProfile: 'Zapisz profil',
    },
    bindings: {
      loading: 'Ładowanie powiązań…',
      saved: 'Powiązania zapisano. Zaktualizuj profile, aby wskazywały zmienione wersje powiązań.',
      intro: 'Mapuj zadeklarowane wyniki do wejść kryteriów. Zmień wersję powiązania podczas edycji jego kontraktu.',
      pinnedContracts: 'Przypięte kontrakty',
      useInstalledVersions: 'Użyj zainstalowanych wersji kontraktów',
      bindingId: 'ID powiązania',
      version: 'Wersja',
      availableOutput: 'Dostępny wynik',
      dimensionVersion: 'Wersja kryterium',
      unavailable: 'niedostępne',
      requiredOutput: 'Wymagany wynik',
      enabled: 'Włączone',
      advancedDetails: 'Szczegóły zaawansowane',
      internalSourcePath: 'Wewnętrzna ścieżka źródła',
      targetPath: 'Pole docelowe → względna ścieżka źródła (lub null)',
      removeBinding: 'Usuń powiązanie',
      addBinding: 'Dodaj powiązanie',
      saving: 'Zapisywanie…',
      saveBindings: 'Zapisz powiązania',
      noOutputs: 'Ta wtyczka nie ma zadeklarowanych wyników kryteriów.',
    },
    runner: {
      evaluate: 'Oceń',
      description: 'Podaj kontekst dla tego uruchomienia. Wynik zostanie zapisany w Observatory.',
      runtimeContext: 'Kontekst decyzji w czasie wykonania',
      pluginInput: 'Wejście możliwości wtyczki',
      evaluating: 'Ocenianie…',
      evaluateAlternatives: 'Oceń alternatywy',
      noAlternative: 'Brak wykonalnej alternatywy',
      inspect: 'Sprawdź decyzję i audyt',
    },
    genericPanel: {
      loading: 'Ładowanie widoku aplikacji…',
      alternative: 'Alternatywa',
      feasible: 'Wykonalna',
      score: 'Ocena',
      rank: 'Ranking',
      requiredActions: 'Wymagane działania',
      yes: 'Tak',
      no: 'Nie',
    },
    schema: {
      invalidJson: 'Wprowadź poprawny JSON przed zapisaniem.',
      configuration: 'Konfiguracja',
      removeItem: 'Usuń element',
      addItem: 'Dodaj element',
    },
    shell: {
      motto: 'Modeluj · łącz · waliduj',
    },
    presentation: {
      sections: {
        overview: 'Przegląd',
        alternatives: 'Alternatywy',
        dimensions: 'Kryteria',
        constraints: 'Ograniczenia',
        policies: 'Polityki',
        compliance: 'Zgodność',
      },
      businessConfigured: 'Skonfigurowane biznesowo',
      dipCalculated: 'Obliczone przez DIP',
      pluginSupplied: 'Dostarczone przez wtyczkę',
      runtimeSupplied: 'Dostarczone w czasie wykonania',
      rule: 'Reguła',
      framework: 'Zestaw reguł',
      action: 'Działanie',
      severity: 'Istotność',
      budgetConstraint: 'Ograniczenie budżetowe',
      budgetHelp: 'Obliczony koszt musi pozostać w skonfigurowanym budżecie.',
    },
  },
} as const

export function studioCopy(locale: StudioLocale) {
  return STUDIO_COPY[locale]
}
