"use client";

import { useState } from "react";
import { Activity, ArrowRight, BrainCircuit, CheckCircle2, ChevronRight, Clock3, Info, Play, RotateCcw, ShieldAlert, SlidersHorizontal, Target } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { cn } from "@/lib/utils";
import type { Locale } from "@/lib/observatory-i18n";

type Inputs = { demandChangePct: number; materialAvailabilityPct: number; productionCapacityPct: number; machineAvailabilityPct: number };
type DecisionResult = {
  audit_id: string; event_id: string; decision: string; rule: string; matched_conditions: number; total_conditions: number; explanation: string[]; timestamp: string;
  rules_executed: Array<{ rule_name: string; matched: boolean; conditions_total: number; conditions_matched: number; evidence: Array<{ feature: string; operator: string; threshold: number | string | boolean | Array<number | string | boolean>; actual_value: number | string | boolean | null; passed: boolean }> }>;
};
type Stage = "idle" | "inputs" | "evaluating" | "decision" | "error";

const INITIAL_INPUTS: Inputs = { demandChangePct: 7, materialAvailabilityPct: 88, productionCapacityPct: 86, machineAvailabilityPct: 94 };
const STAGES = ["INPUTS", "EVALUATION", "DECISION"] as const;

function SliderField({ label, value, min, max, step = 1, unit, onChange }: { label: string; value: number; min: number; max: number; step?: number; unit: string; onChange: (value: number) => void }) {
  const percentage = ((value - min) / (max - min)) * 100;
  return (
    <div className="space-y-2">
      <div className="flex items-end justify-between gap-3"><label className="text-xs font-medium text-slate-300">{label}</label><span className="text-sm font-semibold tabular-nums text-white">{value}{unit}</span></div>
      <input type="range" min={min} max={max} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} className="w-full accent-cyan-300" style={{ background: `linear-gradient(to right, rgb(103 232 249) ${percentage}%, rgb(255 255 255 / 0.08) ${percentage}%)` }} aria-label={label} />
      <div className="flex justify-between text-[10px] tabular-nums text-slate-600"><span>{min}{unit}</span><span>{max}{unit}</span></div>
    </div>
  );
}

function featureLabel(feature: string) { return feature.replaceAll("_pct", "").replaceAll("_", " "); }

export function WspDemandForecastWorkspace({ locale }: { locale: Locale }) {
  const [inputs, setInputs] = useState<Inputs>(INITIAL_INPUTS);
  const [stage, setStage] = useState<Stage>("idle");
  const [result, setResult] = useState<DecisionResult | null>(null);
  const [history, setHistory] = useState<Array<{ id: string; inputs: Inputs; decision: string }>>([]);
  const [error, setError] = useState<string | null>(null);

  const copy = locale === "pl" ? {
    eyebrow: "WSP PROTOTYP", title: "Production State → Decision", subtitle: "Zmień stan operacyjny, uruchom silnik i zobacz decyzję wygenerowaną przez DIP.", demo: "Dane demonstracyjne — do walidacji na danych WSP", demand: "Zmiana popytu", material: "Dostępność materiału", capacity: "Zdolność produkcyjna", machine: "Dostępność maszyn", run: "Uruchom decyzję", running: "DIP analizuje…", reset: "Reset", decision: "DECISION ENGINE", recommendation: "Rekomendacja", trace: "Ślad wykonania DIP", evidence: "Dowody warunków", history: "Historia uruchomień", ready: "Gotowe do uruchomienia", error: "Nie udało się wykonać decyzji", human: "HUMAN-IN-THE-LOOP", real: "Real execution · DIP Core", initial: "Ustaw parametry i uruchom decyzję.", changed: "Stan wejściowy zmieniony — uruchom DIP ponownie.", noData: "Brak wyników"
  } : {
    eyebrow: "WSP PROTOTYPE", title: "Production State → Decision", subtitle: "Change the operational state, run the engine, and see a decision generated by DIP.", demo: "Demonstration data — to be validated on WSP data", demand: "Demand change", material: "Material availability", capacity: "Production capacity", machine: "Machine availability", run: "Run decision", running: "DIP is evaluating…", reset: "Reset", decision: "DECISION ENGINE", recommendation: "Recommendation", trace: "DIP execution trace", evidence: "Condition evidence", history: "Run history", ready: "Ready to run", error: "Decision execution failed", human: "HUMAN-IN-THE-LOOP", real: "Real execution · DIP Core", initial: "Set the operating parameters and run the decision.", changed: "Input state changed — run DIP again.", noData: "No result yet"
  };

  const setInput = <K extends keyof Inputs>(key: K, value: Inputs[K]) => { setInputs((current) => ({ ...current, [key]: value })); setStage("idle"); setError(null); };

  async function runDecision() {
    setStage("inputs"); setError(null); setResult(null);
    await new Promise((resolve) => window.setTimeout(resolve, 350));
    setStage("evaluating");
    try {
      const response = await fetch("/api/dip/production-decision", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(inputs) });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.error ?? "DIP request failed");
      await new Promise((resolve) => window.setTimeout(resolve, 300));
      setResult(payload as DecisionResult); setStage("decision");
      setHistory((current) => [{ id: payload.audit_id, inputs: { ...inputs }, decision: payload.decision }, ...current].slice(0, 5));
    } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to execute DIP decision"); setStage("error"); }
  }

  function reset() { setInputs(INITIAL_INPUTS); setStage("idle"); setResult(null); setError(null); setHistory([]); }

  return (
    <main className="min-h-screen bg-slate-950 px-4 py-8 text-white md:px-8">
      <div className="mx-auto max-w-[1500px] space-y-6">
        <header className="flex flex-col gap-4 border-b border-white/8 pb-6 lg:flex-row lg:items-end lg:justify-between">
          <div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.22em] text-cyan-400"><BrainCircuit className="h-4 w-4" />{copy.eyebrow}</div><h1 className="mt-2 text-3xl font-semibold tracking-tight md:text-4xl">{copy.title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{copy.subtitle}</p></div>
          <div className="flex flex-wrap gap-2"><Badge variant="amber">{copy.demo}</Badge><Badge variant="emerald">{copy.real}</Badge></div>
        </header>

        <section className="grid gap-4 xl:grid-cols-[1.05fr_.95fr]">
          <Card className="border-white/8 bg-white/[0.03]"><CardHeader><div className="flex items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-cyan-300"><SlidersHorizontal className="h-4 w-4" /><CardTitle>Operational state</CardTitle></div><p className="mt-1 text-sm text-slate-500">{stage === "idle" && result ? copy.changed : copy.initial}</p></div><Button variant="ghost" size="icon" onClick={reset} aria-label={copy.reset}><RotateCcw className="h-4 w-4" /></Button></div></CardHeader>
            <CardContent className="space-y-7"><SliderField label={copy.demand} value={inputs.demandChangePct} min={-15} max={15} unit="%" onChange={(value) => setInput("demandChangePct", value)} /><SliderField label={copy.material} value={inputs.materialAvailabilityPct} min={50} max={100} unit="%" onChange={(value) => setInput("materialAvailabilityPct", value)} /><SliderField label={copy.capacity} value={inputs.productionCapacityPct} min={60} max={100} unit="%" onChange={(value) => setInput("productionCapacityPct", value)} /><SliderField label={copy.machine} value={inputs.machineAvailabilityPct} min={70} max={100} unit="%" onChange={(value) => setInput("machineAvailabilityPct", value)} />
              <Button onClick={runDecision} disabled={stage === "inputs" || stage === "evaluating"} className="h-12 w-full gap-2 text-sm font-semibold">{stage === "inputs" || stage === "evaluating" ? <Activity className="h-4 w-4 animate-pulse" /> : <Play className="h-4 w-4" />}{stage === "inputs" || stage === "evaluating" ? copy.running : copy.run}</Button>
            </CardContent>
          </Card>

          <Card className="border-cyan-300/15 bg-cyan-300/[0.035]"><CardHeader><div className="flex items-center justify-between"><CardTitle>{copy.decision}</CardTitle><Badge variant={stage === "decision" ? "emerald" : stage === "error" ? "rose" : "neutral"}>{stage === "decision" ? "READY" : stage === "error" ? "ERROR" : "WAITING"}</Badge></div></CardHeader><CardContent>
              <div className="mb-6 grid grid-cols-3 gap-2">{STAGES.map((item, index) => { const active = (stage === "inputs" && index === 0) || (stage === "evaluating" && index === 1) || (stage === "decision" && index === 2) || (stage === "idle" && index === 0); const done = (stage === "evaluating" && index === 0) || (stage === "decision" && index < 2); return <div key={item} className="space-y-2"><div className={cn("h-1 rounded-full transition-all duration-500", active || done ? "bg-cyan-300" : "bg-white/8")} /><div className={cn("text-[10px] font-semibold tracking-[0.16em]", active || done ? "text-cyan-300" : "text-slate-600")}>{item}</div></div>; })}</div>
              {error ? <div className="rounded-2xl border border-rose-300/20 bg-rose-300/5 p-5"><div className="flex items-center gap-2 text-rose-300"><ShieldAlert className="h-4 w-4" /><span className="font-semibold">{copy.error}</span></div><p className="mt-2 break-words text-sm text-slate-400">{error}</p></div> : result ? <div className="space-y-5"><div className="rounded-2xl border border-emerald-300/20 bg-emerald-300/[0.05] p-5"><div className="text-[10px] font-semibold uppercase tracking-[0.2em] text-emerald-300">{copy.recommendation}</div><div className="mt-2 flex items-start gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-emerald-300" /><h2 className="text-xl font-semibold leading-7">{result.decision}</h2></div><div className="mt-4 flex flex-wrap gap-2"><Badge variant="emerald">Rule: {result.rule}</Badge><Badge variant="neutral">{result.matched_conditions}/{result.total_conditions} conditions</Badge></div></div><div className="rounded-2xl border border-white/8 bg-black/10 p-4"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-slate-500"><Clock3 className="h-3.5 w-3.5" />{copy.trace}</div><div className="mt-3 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><div><div className="text-slate-600">Audit</div><div className="mt-1 truncate text-slate-300">{result.audit_id}</div></div><div><div className="text-slate-600">Rule</div><div className="mt-1 text-slate-300">{result.rule}</div></div><div><div className="text-slate-600">Conditions</div><div className="mt-1 text-slate-300">{result.matched_conditions}/{result.total_conditions}</div></div><div><div className="text-slate-600">Event</div><div className="mt-1 truncate text-slate-300">{result.event_id}</div></div></div></div></div> : <div className="flex min-h-[260px] flex-col items-center justify-center text-center"><Target className="h-8 w-8 text-cyan-300/50" /><p className="mt-3 text-sm text-slate-500">{copy.ready}</p><p className="mt-1 max-w-sm text-xs leading-5 text-slate-600">{copy.initial}</p></div>}
            </CardContent></Card>
        </section>

        {result && <section className="grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><Card className="border-white/8 bg-white/[0.025]"><CardHeader><div className="flex items-center gap-2"><Info className="h-4 w-4 text-cyan-300" /><CardTitle>{copy.evidence}</CardTitle></div></CardHeader><CardContent className="space-y-3">{result.rules_executed.map((trace) => <div key={trace.rule_name} className="rounded-xl border border-white/7 bg-black/10 p-3"><div className="flex items-center justify-between gap-3"><span className="text-xs font-semibold text-slate-300">{trace.rule_name}</span><Badge variant={trace.matched ? "emerald" : "neutral"}>{trace.matched ? "MATCH" : "NO MATCH"}</Badge></div><div className="mt-3 space-y-2">{trace.evidence.map((item) => <div key={`${trace.rule_name}-${item.feature}`} className="flex items-center justify-between gap-3 text-xs"><span className="text-slate-500">{featureLabel(item.feature)}</span><span className={cn("tabular-nums", item.passed ? "text-emerald-300" : "text-slate-400")}>{String(item.actual_value)} {item.operator} {String(item.threshold)}</span></div>)}</div></div>)}</CardContent></Card>
          <Card className="border-white/8 bg-white/[0.025]"><CardHeader><div className="flex items-center gap-2"><ChevronRight className="h-4 w-4 text-cyan-300" /><CardTitle>{copy.history}</CardTitle></div></CardHeader><CardContent className="space-y-2">{history.length ? history.map((item, index) => <div key={item.id} className="rounded-xl border border-white/7 bg-black/10 p-3"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] uppercase tracking-[0.16em] text-slate-600">Run #{history.length - index}</div><div className="mt-1 text-sm font-medium text-slate-200">{item.decision}</div></div><ArrowRight className="mt-1 h-4 w-4 text-slate-600" /></div><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-[10px] text-slate-600"><span>Demand {item.inputs.demandChangePct}%</span><span>Material {item.inputs.materialAvailabilityPct}%</span><span>Capacity {item.inputs.productionCapacityPct}%</span><span>Machine {item.inputs.machineAvailabilityPct}%</span></div></div>) : <div className="py-10 text-center text-xs text-slate-600">{copy.noData}</div>}</CardContent></Card></section>}

        <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-white/7 pt-4 text-[10px] uppercase tracking-[0.16em] text-slate-600"><span>{copy.human}</span><span>production-decision-v0.1 · inline workflow · DIP Core</span></footer>
      </div>
    </main>
  );
}
