import type { MarketingLocale } from "./qdip-copy";
import styles from "./decision-space-story.module.css";

const copy={
 en:{eyebrow:"A decision is a space, not a score",title:"See the trade-offs before you decide.",body:"QDIP keeps alternatives, constraints and uncertainty visible instead of collapsing them into a black-box answer.",items:[["01","Frame","What is happening, what matters, and what limits the choice."],["02","Compare","See alternatives against the same objectives and constraints."],["03","Explain","Understand why one option is recommended and where uncertainty remains."],["04","Decide","The recommendation informs the responsible human — it does not replace them."]]},
 uk:{eyebrow:"Рішення — це простір, а не оцінка",title:"Побачте компроміси до того, як прийняти рішення.",body:"QDIP залишає альтернативи, обмеження та невизначеність видимими, замість того щоб зводити їх до непрозорої відповіді.",items:[["01","Сформулюйте","Що відбувається, що важливо та що обмежує вибір."],["02","Порівняйте","Оцініть альтернативи за спільними цілями та обмеженнями."],["03","Поясніть","Зрозумійте, чому рекомендовано певний варіант і де лишається невизначеність."],["04","Вирішіть","Рекомендація допомагає відповідальній людині, а не замінює її."]]},
 pl:{eyebrow:"Decyzja to przestrzeń, nie wynik",title:"Zobacz kompromisy, zanim podejmiesz decyzję.",body:"QDIP utrzymuje alternatywy, ograniczenia i niepewność w polu widzenia, zamiast redukować je do odpowiedzi z czarnej skrzynki.",items:[["01","Określ","Co się dzieje, co ma znaczenie i co ogranicza wybór."],["02","Porównaj","Oceń alternatywy według tych samych celów i ograniczeń."],["03","Wyjaśnij","Zrozum, dlaczego rekomendowana jest dana opcja i gdzie pozostaje niepewność."],["04","Zdecyduj","Rekomendacja wspiera odpowiedzialną osobę — nie zastępuje jej."]]}
} as const;
export function DecisionSpaceStory({locale}:{locale:MarketingLocale}){const c=copy[locale];return <section className={styles.story}><div className={styles.intro}><span>{c.eyebrow}</span><h2>{c.title}</h2><p>{c.body}</p></div><div className={styles.steps}>{c.items.map(([n,t,b])=><article key={n}><b>{n}</b><div><h3>{t}</h3><p>{b}</p></div></article>)}</div></section>}
