import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { marketingLocaleHref, observatoryHref } from "@/lib/platform-urls";
import { marketingCopy, marketingLocales, type MarketingLocale } from "./qdip-copy";
import { QdipLogo } from "./qdip-logo";
import styles from "./qdip-site.module.css";

const labels: Record<MarketingLocale,{decision:string;context:string;alternatives:string;objectives:string;effects:string;costs:string;risk:string;uncertainty:string;constraints:string;recommendation:string;human:string;see:string;describe:string;core:string;architecture:string;model:string;explain:string;research:string}>={
 en:{decision:"Describe your decision",context:"Context",alternatives:"Alternatives",objectives:"Objectives",effects:"Expected effects",costs:"Costs",risk:"Risk",uncertainty:"Uncertainty",constraints:"Constraints",recommendation:"Recommendation",human:"Human decision",see:"See QDIP in action",describe:"Describe your decision",core:"QDIP Core",architecture:"Architecture",model:"Decision model",explain:"Explainability",research:"Research"},
 uk:{decision:"Описати ваше рішення",context:"Контекст",alternatives:"Альтернативи",objectives:"Цілі",effects:"Очікувані ефекти",costs:"Вартість",risk:"Ризик",uncertainty:"Невизначеність",constraints:"Обмеження",recommendation:"Рекомендація",human:"Рішення людини",see:"Подивитися QDIP у дії",describe:"Описати ваше рішення",core:"QDIP Core",architecture:"Архітектура",model:"Модель рішення",explain:"Пояснюваність",research:"Дослідження"},
 pl:{decision:"Opisz swoją decyzję",context:"Kontekst",alternatives:"Alternatywy",objectives:"Cele",effects:"Oczekiwane efekty",costs:"Koszty",risk:"Ryzyko",uncertainty:"Niepewność",constraints:"Ograniczenia",recommendation:"Rekomendacja",human:"Decyzja człowieka",see:"Zobacz QDIP w działaniu",describe:"Opisz swoją decyzję",core:"QDIP Core",architecture:"Architektura",model:"Model decyzji",explain:"Wyjaśnialność",research:"Badania"}
};
const href=(l:MarketingLocale,s:string)=>`${marketingLocaleHref(l)}/${s}`;

function Shell({locale,children}:{locale:MarketingLocale;children:React.ReactNode}){const c=marketingCopy[locale];return <main className={styles.site} lang={locale}><header className={styles.header}><div className={styles.headerInner}><Link className={styles.brand} href={marketingLocaleHref(locale)}><QdipLogo/></Link><nav className={styles.nav} aria-label="Primary navigation"><Link href={href(locale,"how-it-works")}>{c.nav[0]}</Link><Link href={href(locale,"use-cases")}>{c.nav[1]}</Link><Link href={href(locale,"core")}>{c.nav[3]}</Link></nav><nav className={styles.languageNav} aria-label="Language">{marketingLocales.map(x=><a key={x} aria-current={x===locale?"page":undefined} href={marketingLocaleHref(x)}>{x==="uk"?"UA":x.toUpperCase()}</a>)}</nav></div></header>{children}<footer className={styles.footer}><QdipLogo/><nav><Link href={href(locale,"how-it-works")}>{c.nav[0]}</Link><Link href={href(locale,"use-cases")}>{c.nav[1]}</Link><Link href={href(locale,"core")}>QDIP Core</Link><Link href={href(locale,"core/research")}>{labels[locale].research}</Link></nav><span>© {new Date().getFullYear()} QDIP</span></footer></main>}
function PageHero({eyebrow,title,body}:{eyebrow:string;title:string;body:string}){return <section className={styles.section}><div className={styles.sectionIntro}><div className={styles.eyebrow}>{eyebrow}</div><h2>{title}</h2><p className={styles.centerCopy}>{body}</p></div></section>}
function CoreNav({l}:{l:MarketingLocale}){const x=labels[l];return <div className={styles.centerAction}><Link className={styles.secondaryButton} href={href(l,"core/architecture")}>{x.architecture}</Link> <Link className={styles.secondaryButton} href={href(l,"core/decision-model")}>{x.model}</Link> <Link className={styles.secondaryButton} href={href(l,"core/explainability")}>{x.explain}</Link> <Link className={styles.secondaryButton} href={href(l,"core/research")}>{x.research}</Link></div>}

export function PublicPage({locale,slug}:{locale:MarketingLocale;slug:string}){const x=labels[locale],c=marketingCopy[locale];
 if(slug==="how-it-works") return <Shell locale={locale}><PageHero eyebrow={c.nav[0]} title={c.hero[1]} body={c.hero[3]}/><section className={styles.section}><div className={styles.valueGrid}>{[x.context,x.alternatives,x.objectives,x.effects,x.costs,x.risk,x.uncertainty,x.constraints,x.recommendation].map((v,i)=><article key={v}><h3>{i+1}. {v}</h3><p>{["What is happening now and what evidence is available?","What can actually be done?","What outcomes matter?","What is expected under each alternative?","What does each alternative require?","What can go wrong and with what consequence?","What do we not know confidently?","What options are impossible or unacceptable?","QDIP evaluates the alternatives using the configured decision model."][i]}</p></article>)}</div><PageHero eyebrow="10" title={x.human} body={c.hero[4]}/><div className={styles.centerAction}><Link className={styles.primaryButtonLarge} href={href(locale,"use-cases")}>{x.see}</Link></div></section></Shell>;
 if(slug==="use-cases") return <Shell locale={locale}><PageHero eyebrow={c.nav[1]} title={c.cases[0]} body="Different domains. The same underlying decision structure."/><section className={styles.section}><div className={styles.caseGrid}><article className={styles.featuredCase}><span>{c.cases[1]}</span><h3>{c.cases[2]}</h3><strong>{c.cases[3]}</strong><p>{c.cases[4]}</p><Link href={observatoryHref(`${locale==="uk"?"en":locale}/resource-allocation`)}>{c.cases[5]} <ArrowRight size={15}/></Link></article><article><span>{c.cases[6]}</span><h3>{c.cases[7]}</h3><strong>{c.cases[8]}</strong><p>{c.cases[9]}</p><Link href={observatoryHref(`${locale==="uk"?"en":locale}/gas-forecast`)}>{c.cases[10]} <ArrowRight size={15}/></Link></article><article><span>{c.cases[11]}</span><h3>{c.cases[12]}</h3><strong>{c.cases[13]}</strong><p className={styles.comingSoon}>{c.cases[14]}</p></article></div><PageHero eyebrow="QDIP" title="State → alternatives → objectives → effects → costs → risk → uncertainty → constraints" body="QDIP evaluates the available alternatives and produces a recommendation with evidence."/><div className={styles.centerAction}><Link className={styles.primaryButtonLarge} href={href(locale,"decision")}>{x.describe}</Link></div></section></Shell>;
 if(slug==="decision") return <Shell locale={locale}><PageHero eyebrow="QDIP" title={c.conversion[0]} body={c.conversion[1]}/><section className={styles.section}><form className={styles.valueGrid} action="mailto:contact@qdip.ai" method="post" encType="text/plain"><label>Name<input name="name" required/></label><label>Organization<input name="organization"/></label><label>Email<input name="email" type="email" required/></label><label>What decision does your team make repeatedly?<textarea name="decision" required/></label><label>What information is used?<textarea name="information"/></label><label>What alternatives are usually considered?<textarea name="alternatives"/></label><label>What constraints matter?<textarea name="constraints"/></label><label>Additional context<textarea name="context"/></label><button className={styles.primaryButtonLarge} type="submit">{x.describe}</button></form></section></Shell>;
 const core=slug==="core"||slug.startsWith("core/"); if(core){const sub=slug.split("/")[1]??"";const content=sub==="architecture"?[x.architecture,"Inputs / features → Decision context → Decision Engine → alternative evaluation → recommendation → evidence / trace / audit.","The public architecture describes boundaries and execution flow without exposing demo-specific domain logic."]:sub==="decision-model"?[x.model,"State, alternatives, objectives, expected effects, costs, risk, uncertainty, constraints and evidence form the reusable decision abstraction.","The decision model is distinct from implementation architecture and from individual demo logic."]:sub==="explainability"?[x.explain,"Why was this alternative recommended?", "QDIP keeps evidence and the evaluated decision path inspectable so a responsible person can review the recommendation. Explainability is part of decision governance, not a marketing badge."]:sub==="research"?[x.research,"Applied research into repeatable decisions under constraints and uncertainty.","Public experiments currently include Gas and Resource Allocation. Claims are limited to implemented demonstrations; no publication, institutional validation or customer outcome is implied."]:[x.core,"A runtime for explainable decision systems.","QDIP Core provides the technical foundation for evaluating alternatives and returning recommendations with inspectable evidence. The responsible person retains final authority."];return <Shell locale={locale}><PageHero eyebrow={x.core} title={content[0]} body={content[1]}/><section className={styles.section}><p className={styles.centerCopy}>{content[2]}</p><CoreNav l={locale}/></section></Shell>}
 return null;
}
