export const marketingLocales = ["en", "uk", "pl"] as const;
export type MarketingLocale = (typeof marketingLocales)[number];

export const marketingCopy = {
  en: {
    nav: ["How it works", "Use cases", "Why QDIP", "Technology", "See demos"],
    hero: ["Decision Engine", "Make complex decisions repeatable.", "Your team already has the information. QDIP helps decide what to do next.", "When a recurring decision involves multiple alternatives, priorities, constraints and uncertainty, QDIP evaluates the available options and prepares an explainable recommendation.", "Your team makes the final decision.", "See QDIP in action"],
    problem: ["Does your team repeatedly make decisions like these?", "Which requests should receive limited resources?", "Which opportunity deserves attention first?", "Should we act now, wait, or choose another option?", "Which alternative best satisfies our priorities and constraints?", "These decisions become difficult when objectives compete, resources are limited, rules constrain the available options, and some evidence is uncertain.", "QDIP provides a consistent way to evaluate those choices."],
    compare: ["Without a Decision Engine", "Human reasoning carries the full comparison", "With QDIP", "Recommendation + evidence support the human decision"],
    how: ["How it works", "Context", "Alternatives", "Evaluation", "Recommendation", "Human decision", "How QDIP works"],
    cases: ["One Decision Engine. Different decisions.", "ALLOCATE", "Resource Allocation", "Where should limited resources go?", "Evaluate competing needs against priorities, available capabilities, capacity and constraints.", "Explore Resource Allocation", "DECIDE", "Gas Decision", "Act now, wait, or choose another strategy?", "Compare available actions under changing conditions and uncertainty.", "Explore Gas", "PRIORITIZE", "GTM Lab", "Which opportunities deserve attention first?", "Coming soon"],
    why: ["Why QDIP", "Consistent", "Apply the same decision model consistently.", "Explainable", "Understand why an alternative was recommended.", "Constraint-aware", "Evaluate decisions within explicit real-world limitations.", "Uncertainty-aware", "Represent uncertainty rather than silently treating uncertain evidence as fact.", "Inspectable", "Compare alternatives and their trade-offs.", "Human-controlled", "QDIP recommends. The responsible person decides."],
    adoption: ["Start with one decision.", "One recurring decision", "Model it", "Test real scenarios", "Compare QDIP recommendations with current decisions", "Measure value", "Expand if useful"],
    conversion: ["What decision does your team make repeatedly?", "Show us one recurring decision, the information used to make it, and the constraints that matter. We can determine whether it is a good fit for QDIP.", "Describe your decision"],
  },
  uk: {
    nav: ["Як це працює", "Сценарії", "Чому QDIP", "Технологія", "Демо"],
    hero: ["Рушій прийняття рішень", "Зробіть складні рішення повторюваними.", "У вашої команди вже є інформація. QDIP допомагає визначити, що робити далі.", "Коли повторюване рішення має кілька альтернатив, пріоритетів, обмежень і невизначеність, QDIP оцінює доступні варіанти та готує пояснювану рекомендацію.", "Остаточне рішення приймає ваша команда.", "Подивитися QDIP у дії"],
    problem: ["Ваша команда регулярно приймає такі рішення?", "Які запити мають отримати обмежені ресурси?", "Яка можливість заслуговує уваги першою?", "Діяти зараз, чекати чи обрати інший варіант?", "Яка альтернатива найкраще відповідає пріоритетам та обмеженням?", "Такі рішення ускладнюються, коли цілі конкурують, ресурси обмежені, правила звужують вибір, а частина доказів невизначена.", "QDIP дає послідовний спосіб оцінювати такий вибір."],
    compare: ["Без рушія прийняття рішень", "Усе порівняння тримається на людському міркуванні", "З QDIP", "Рекомендація та докази підтримують рішення людини"],
    how: ["Як це працює", "Контекст", "Альтернативи", "Оцінювання", "Рекомендація", "Рішення людини", "Як працює QDIP"],
    cases: ["Один рушій. Різні рішення.", "РОЗПОДІЛИТИ", "Розподіл ресурсів", "Куди спрямувати обмежені ресурси?", "Оцінюйте конкуруючі потреби за пріоритетами, можливостями, потужністю та обмеженнями.", "Відкрити Resource Allocation", "ВИРІШИТИ", "Gas Decision", "Діяти зараз, чекати чи обрати іншу стратегію?", "Порівнюйте доступні дії за мінливих умов та невизначеності.", "Відкрити Gas", "ПРІОРИТЕЗУВАТИ", "GTM Lab", "Які можливості заслуговують уваги першими?", "Незабаром"],
    why: ["Чому QDIP", "Послідовність", "Застосовуйте ту саму модель рішення послідовно.", "Пояснюваність", "Розумійте, чому рекомендовано альтернативу.", "Урахування обмежень", "Оцінюйте рішення в межах явних реальних обмежень.", "Урахування невизначеності", "Представляйте невизначеність явно, а не як факт.", "Перевірюваність", "Порівнюйте альтернативи та компроміси.", "Контроль людини", "QDIP рекомендує. Відповідальна людина вирішує."],
    adoption: ["Почніть з одного рішення.", "Одне повторюване рішення", "Змоделюйте його", "Перевірте реальні сценарії", "Порівняйте рекомендації QDIP з поточними рішеннями", "Виміряйте цінність", "Розширюйте, якщо корисно"],
    conversion: ["Яке рішення ваша команда приймає регулярно?", "Опишіть одне повторюване рішення, інформацію для нього та важливі обмеження. Ми визначимо, чи підходить для нього QDIP.", "Описати ваше рішення"],
  },
  pl: {
    nav: ["Jak to działa", "Przypadki użycia", "Dlaczego QDIP", "Technologia", "Demo"],
    hero: ["Silnik decyzyjny", "Spraw, by złożone decyzje były powtarzalne.", "Twój zespół ma już informacje. QDIP pomaga zdecydować, co zrobić dalej.", "Gdy powtarzalna decyzja obejmuje wiele alternatyw, priorytetów, ograniczeń i niepewność, QDIP ocenia dostępne opcje i przygotowuje wyjaśnialną rekomendację.", "Ostateczną decyzję podejmuje Twój zespół.", "Zobacz QDIP w działaniu"],
    problem: ["Czy Twój zespół regularnie podejmuje takie decyzje?", "Które potrzeby powinny otrzymać ograniczone zasoby?", "Która szansa zasługuje na uwagę jako pierwsza?", "Działać teraz, czekać czy wybrać inną opcję?", "Która alternatywa najlepiej spełnia priorytety i ograniczenia?", "Decyzje stają się trudne, gdy cele konkurują, zasoby są ograniczone, reguły zawężają opcje, a część dowodów jest niepewna.", "QDIP zapewnia spójny sposób oceny tych wyborów."],
    compare: ["Bez silnika decyzyjnego", "Całe porównanie opiera się na rozumowaniu człowieka", "Z QDIP", "Rekomendacja i dowody wspierają decyzję człowieka"],
    how: ["Jak to działa", "Kontekst", "Alternatywy", "Ocena", "Rekomendacja", "Decyzja człowieka", "Jak działa QDIP"],
    cases: ["Jeden silnik decyzyjny. Różne decyzje.", "ALOKUJ", "Resource Allocation", "Gdzie skierować ograniczone zasoby?", "Oceniaj konkurujące potrzeby względem priorytetów, możliwości, pojemności i ograniczeń.", "Poznaj Resource Allocation", "DECYDUJ", "Gas Decision", "Działać teraz, czekać czy wybrać inną strategię?", "Porównuj dostępne działania w zmiennych warunkach i przy niepewności.", "Poznaj Gas", "PRIORYTETYZUJ", "GTM Lab", "Które szanse zasługują na uwagę jako pierwsze?", "Wkrótce"],
    why: ["Dlaczego QDIP", "Spójny", "Stosuj ten sam model decyzji w sposób spójny.", "Wyjaśnialny", "Rozumiej, dlaczego rekomendowano alternatywę.", "Uwzględnia ograniczenia", "Oceniaj decyzje w ramach jawnych ograniczeń świata rzeczywistego.", "Uwzględnia niepewność", "Reprezentuj niepewność zamiast traktować ją jak fakt.", "Kontrolowalny", "Porównuj alternatywy i kompromisy.", "Kontrolowany przez człowieka", "QDIP rekomenduje. Odpowiedzialna osoba decyduje."],
    adoption: ["Zacznij od jednej decyzji.", "Jedna powtarzalna decyzja", "Zamodeluj ją", "Testuj rzeczywiste scenariusze", "Porównaj rekomendacje QDIP z obecnymi decyzjami", "Zmierz wartość", "Rozszerz, jeśli to użyteczne"],
    conversion: ["Jaką decyzję Twój zespół podejmuje regularnie?", "Opisz jedną powtarzalną decyzję, używane informacje i istotne ograniczenia. Możemy określić, czy QDIP jest dobrym dopasowaniem.", "Opisz swoją decyzję"],
  },
} as const;
