export const marketingLocales = ["en", "uk", "pl"] as const;
export type MarketingLocale = (typeof marketingLocales)[number];

export const marketingCopy = {
  en: {
    nav: ["How it works", "Use cases", "Why QDIP", "Technology", "See demos"],
    hero: ["Decision Engine", "Make complex decisions repeatable.", "Your team already has the information. QDIP helps decide what to do next.", "When a recurring decision involves several options, competing priorities, constraints and uncertainty, QDIP evaluates the available choices and provides a recommendation with supporting evidence.", "Your team makes the final decision.", "See QDIP in action"],
    diagram: ["Information", "Alternatives", "Priorities", "Constraints", "Decision Engine", "Recommendation", "supporting evidence", "Human decision"],
    problem: ["Does your team repeatedly make decisions like these?", "Which requests should receive limited resources?", "Which opportunity deserves attention first?", "Should we act now, wait, or choose another option?", "Which option should we choose when priorities conflict?", "These decisions become difficult when objectives compete, resources are limited, rules constrain the available options, and some information remains uncertain.", "QDIP provides a consistent way to evaluate those choices."],
    bridge: "The challenge isn’t having more information. It’s evaluating the same kind of decision consistently when priorities, constraints and evidence change.",
    compare: ["Without a Decision Engine", "Human reasoning carries the full comparison", "With QDIP", "A recommendation and supporting evidence inform the human decision"],
    how: ["How it works", "Context", "Alternatives", "Evaluation", "Recommendation", "Human decision", "How QDIP works"],
    cases: ["One Decision Engine. Different decisions.", "ALLOCATE", "Resource Allocation", "Where should limited resources go?", "Evaluate competing needs against priorities, available resources and constraints.", "Explore Resource Allocation", "DECIDE", "Gas Decision", "Act now, wait, or choose another strategy?", "Compare available actions under changing conditions and uncertainty.", "Explore Gas", "PRIORITIZE", "GTM Lab", "Which opportunities deserve attention first?", "Coming soon"],
    why: ["Why QDIP", "Consistent", "Apply the same decision model consistently. Reduce dependence on who happens to be making the decision.", "Explainable", "Understand why an alternative was recommended. Review and justify important decisions.", "Constraint-aware", "Evaluate alternatives within explicit operational limits. Avoid recommendations that cannot be executed.", "Uncertainty-aware", "Make uncertainty visible. Know where a decision depends on incomplete or uncertain information.", "Inspectable", "Compare alternatives and trade-offs. See what is gained and sacrificed by each choice.", "Human-controlled", "QDIP recommends. The responsible person decides. Authority and accountability stay with your organization."],
    adoption: ["Start with one decision.", "One recurring decision", "Model it", "Test real scenarios", "Compare QDIP recommendations with current decisions", "Measure value", "Expand if useful"],
    conversion: ["What decision does your team make repeatedly?", "Show us one recurring decision, the information used to make it, and the constraints that matter. We can determine whether it is a good fit for QDIP.", "Describe your decision"],
  },
  uk: {
    nav: ["Як це працює", "Сценарії", "Чому QDIP", "Технологія", "Демо"],
    hero: ["Рушій прийняття рішень", "Приймайте складні рішення послідовно.", "У вашої команди вже є інформація. QDIP допомагає визначити, що робити далі.", "Коли регулярне рішення передбачає кілька варіантів, суперечливі пріоритети, обмеження та невизначеність, QDIP оцінює доступні варіанти й надає рекомендацію з обґрунтуванням.", "Остаточне рішення приймає ваша команда.", "Подивитися QDIP у дії"],
    diagram: ["Інформація", "Альтернативи", "Пріоритети", "Обмеження", "Рушій рішень", "Рекомендація", "обґрунтування", "Рішення людини"],
    problem: ["Ваша команда регулярно приймає такі рішення?", "Які запити мають отримати обмежені ресурси?", "Яка можливість потребує уваги першою?", "Діяти зараз, зачекати чи обрати інший варіант?", "Який варіант обрати, коли пріоритети суперечать один одному?", "Такі рішення ускладнюються, коли цілі конкурують, ресурси обмежені, правила звужують вибір, а частина інформації залишається невизначеною.", "QDIP дає послідовний спосіб оцінювати такий вибір."],
    bridge: "Проблема не в нестачі інформації. Складність у тому, щоб послідовно оцінювати однотипні рішення, коли змінюються пріоритети, обмеження та вихідні дані.",
    compare: ["Без рушія прийняття рішень", "Усе порівняння залежить від людського міркування", "З QDIP", "Рекомендація та обґрунтування допомагають людині прийняти рішення"],
    how: ["Як це працює", "Контекст", "Альтернативи", "Оцінювання", "Рекомендація", "Рішення людини", "Як працює QDIP"],
    cases: ["Один рушій. Різні рішення.", "РОЗПОДІЛИТИ", "Розподіл ресурсів", "Куди спрямувати обмежені ресурси?", "Оцінюйте конкуруючі потреби з урахуванням пріоритетів, доступних ресурсів та обмежень.", "Відкрити Resource Allocation", "ВИРІШИТИ", "Gas Decision", "Діяти зараз, зачекати чи обрати іншу стратегію?", "Порівнюйте доступні дії за мінливих умов і невизначеності.", "Відкрити Gas", "ПРІОРИТЕЗУВАТИ", "GTM Lab", "Які можливості потребують уваги першими?", "Незабаром"],
    why: ["Чому QDIP", "Послідовність", "Застосовуйте ту саму модель рішення послідовно. Менше залежності від того, хто саме приймає рішення.", "Зрозуміле обґрунтування", "Розумійте, чому рекомендовано певний варіант. Перевіряйте й обґрунтовуйте важливі рішення.", "Урахування обмежень", "Оцінюйте варіанти в межах реальних операційних обмежень. Відсіюйте те, що неможливо виконати.", "Урахування невизначеності", "Робіть невизначеність видимою. Бачте, де рішення залежить від неповної або ненадійної інформації.", "Прозорість вибору", "Порівнюйте варіанти та компроміси. Бачте, що дає і чого коштує кожен вибір.", "Контроль людини", "QDIP рекомендує. Відповідальна людина вирішує. Повноваження та відповідальність залишаються в організації."],
    adoption: ["Почніть з одного рішення.", "Одне регулярне рішення", "Змоделюйте його", "Перевірте реальні сценарії", "Порівняйте рекомендації QDIP з поточними рішеннями", "Оцініть цінність", "Розширюйте використання, якщо це корисно"],
    conversion: ["Яке рішення ваша команда приймає регулярно?", "Опишіть одне регулярне рішення, інформацію, яку ви використовуєте, та важливі обмеження. Ми визначимо, чи підходить для нього QDIP.", "Описати рішення"],
  },
  pl: {
    nav: ["Jak to działa", "Przypadki użycia", "Dlaczego QDIP", "Technologia", "Demo"],
    hero: ["Silnik decyzyjny", "Podejmuj złożone decyzje w sposób powtarzalny.", "Twój zespół ma już potrzebne informacje. QDIP pomaga zdecydować, co zrobić dalej.", "Gdy regularnie podejmowana decyzja obejmuje kilka opcji, sprzeczne priorytety, ograniczenia i niepewność, QDIP ocenia dostępne możliwości i przedstawia rekomendację wraz z uzasadnieniem.", "Ostateczną decyzję podejmuje Twój zespół.", "Zobacz QDIP w działaniu"],
    diagram: ["Informacje", "Alternatywy", "Priorytety", "Ograniczenia", "Silnik decyzyjny", "Rekomendacja", "uzasadnienie", "Decyzja człowieka"],
    problem: ["Czy Twój zespół regularnie podejmuje takie decyzje?", "Które potrzeby powinny otrzymać ograniczone zasoby?", "Która szansa wymaga uwagi w pierwszej kolejności?", "Działać teraz, poczekać czy wybrać inną opcję?", "Którą opcję wybrać, gdy priorytety są ze sobą sprzeczne?", "Takie decyzje są trudne, gdy cele konkurują ze sobą, zasoby są ograniczone, reguły zawężają wybór, a część informacji pozostaje niepewna.", "QDIP zapewnia spójny sposób oceny takich wyborów."],
    bridge: "Problemem nie jest brak informacji. Trudność polega na spójnej ocenie tego samego rodzaju decyzji, gdy zmieniają się priorytety, ograniczenia i dostępne informacje.",
    compare: ["Bez silnika decyzyjnego", "Całe porównanie zależy od ludzkiej oceny", "Z QDIP", "Rekomendacja i uzasadnienie wspierają decyzję człowieka"],
    how: ["Jak to działa", "Kontekst", "Alternatywy", "Ocena", "Rekomendacja", "Decyzja człowieka", "Jak działa QDIP"],
    cases: ["Jeden silnik decyzyjny. Różne decyzje.", "ALOKUJ", "Resource Allocation", "Gdzie skierować ograniczone zasoby?", "Oceniaj konkurujące potrzeby z uwzględnieniem priorytetów, dostępnych zasobów i ograniczeń.", "Poznaj Resource Allocation", "DECYDUJ", "Gas Decision", "Działać teraz, poczekać czy wybrać inną strategię?", "Porównuj dostępne działania w zmiennych warunkach i przy niepewności.", "Poznaj Gas", "PRIORYTETYZUJ", "GTM Lab", "Które szanse wymagają uwagi w pierwszej kolejności?", "Wkrótce"],
    why: ["Dlaczego QDIP", "Spójność", "Stosuj ten sam model decyzji w sposób spójny. Ogranicz zależność od tego, kto akurat podejmuje decyzję.", "Zrozumiałe uzasadnienie", "Rozumiej, dlaczego zarekomendowano daną opcję. Weryfikuj i uzasadniaj ważne decyzje.", "Uwzględnia ograniczenia", "Oceniaj opcje w ramach rzeczywistych ograniczeń operacyjnych. Odrzucaj rozwiązania, których nie da się wykonać.", "Uwzględnia niepewność", "Pokazuj niepewność wprost. Wiedz, gdzie decyzja zależy od niepełnych lub niepewnych informacji.", "Przejrzystość wyboru", "Porównuj opcje i kompromisy. Zobacz, co zyskujesz i z czego rezygnujesz przy każdym wyborze.", "Kontrola człowieka", "QDIP rekomenduje. Odpowiedzialna osoba decyduje. Uprawnienia i odpowiedzialność pozostają w organizacji."],
    adoption: ["Zacznij od jednej decyzji.", "Jedna regularnie podejmowana decyzja", "Zamodeluj ją", "Przetestuj rzeczywiste scenariusze", "Porównaj rekomendacje QDIP z obecnymi decyzjami", "Oceń wartość", "Rozszerz zastosowanie, jeśli ma to sens"],
    conversion: ["Jaką decyzję Twój zespół podejmuje regularnie?", "Opisz jedną regularnie podejmowaną decyzję, wykorzystywane informacje i istotne ograniczenia. Możemy ocenić, czy QDIP pasuje do tego przypadku.", "Opisz swoją decyzję"],
  },
} as const;
