import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { PublicPage } from "@/components/marketing/public-page";
import { marketingLocales, type MarketingLocale } from "@/components/marketing/qdip-copy";

const titles: Record<string,string>={"how-it-works":"How QDIP Works","use-cases":"QDIP Use Cases",decision:"Describe Your Decision",core:"QDIP Core","core/architecture":"QDIP Core Architecture","core/decision-model":"QDIP Decision Model","core/explainability":"QDIP Explainability","core/research":"QDIP Research"};
const descriptions:Record<string,string>={"how-it-works":"How QDIP evaluates alternatives, constraints, risk and uncertainty to prepare an explainable recommendation for a human decision.","use-cases":"Decision patterns for resource allocation, action selection and opportunity prioritization using the QDIP Decision Engine.",decision:"Describe a recurring decision your organization makes and determine whether it is a good fit for QDIP.",core:"Technical overview of QDIP Core, the runtime behind explainable decision systems.","core/architecture":"Architecture, boundaries and execution flow of QDIP Core.","core/decision-model":"The reusable QDIP decision model: state, alternatives, objectives, effects, costs, risk, uncertainty, constraints and evidence.","core/explainability":"How QDIP keeps recommendations, evidence and decision execution inspectable.","core/research":"QDIP applied research direction and implemented decision experiments."};
function isLocale(v:string):v is MarketingLocale{return marketingLocales.includes(v as MarketingLocale)}
export async function generateMetadata({params}:{params:Promise<{locale:string;slug:string[]}>}):Promise<Metadata>{const {locale,slug}=await params;if(!isLocale(locale))return{};const key=slug.join("/");const title=titles[key]??"QDIP";const description=descriptions[key]??"QDIP Decision Engine";const canonical=`https://qdip.ai/${locale}/${key}`;return{title:{absolute:`${title} — QDIP`},description,alternates:{canonical,languages:{en:`https://qdip.ai/en/${key}`,uk:`https://qdip.ai/uk/${key}`,pl:`https://qdip.ai/pl/${key}`}},openGraph:{title:`${title} — QDIP`,description,url:canonical,type:"website"}}}
export default async function Page({params}:{params:Promise<{locale:string;slug:string[]}>}){const {locale,slug}=await params;if(!isLocale(locale))notFound();const key=slug.join("/");if(!titles[key])notFound();return <PublicPage locale={locale} slug={key}/>}
