import { z } from "zod";
import { DipApiError, runDipPlugin } from "@/lib/dip-api";

const priority = z.enum(["critical", "high", "normal"]);
const demand = z.object({ service: z.string().min(1), units: z.number().nonnegative(), priority: priority.default("normal"), program: z.string().nullable().optional() }).strict();
const community = z.object({ id: z.string().min(1), accessible: z.boolean().default(true), max_teams: z.number().int().nonnegative().default(30), demand: z.array(demand).default([]), accessibility: z.record(z.string(), z.boolean()).default({}), daily_demand: z.record(z.string(), z.array(demand)).default({}), allowed_programs: z.array(z.string()).nullable().optional() }).strict();
const team = z.object({ id: z.string().min(1), current_community: z.string().nullable().optional(), skills: z.array(z.string()).default([]), capacity: z.number().nonnegative().default(0), allowed_communities: z.array(z.string()).nullable().optional(), availability: z.record(z.string(), z.boolean()).default({}), daily_capacity: z.record(z.string(), z.number().nonnegative()).default({}), max_daily_capacity: z.number().nonnegative().nullable().optional(), max_travel_cost: z.number().nonnegative().nullable().optional(), max_travel_minutes: z.number().nonnegative().nullable().optional(), cost_per_capacity: z.number().nonnegative().default(0), programs: z.array(z.string()).default([]) }).strict();
const edge = z.object({ from: z.string().min(1), to: z.string().min(1), minutes: z.number().nonnegative().nullable().optional(), cost: z.number().nonnegative().default(0) }).strict();
const scenario = z.object({ unavailable_teams: z.array(z.string()).default([]), inaccessible_communities: z.array(z.string()).default([]), capacity_factor: z.number().nonnegative().nullable().optional() }).strict();
export const resourceAllocationRequestSchema = z.object({ operation: z.enum(["optimize", "evaluate_manual", "simulate", "counterfactual", "capacity_gap"]).default("optimize"), communities: z.array(community).min(1).max(50), teams: z.array(team).min(1).max(30), travel_edges: z.array(edge).default([]), current_allocation: z.record(z.string(), z.string().nullable()).nullable().optional(), manual_allocation: z.record(z.string(), z.unknown()).nullable().optional(), baseline_allocation: z.record(z.string(), z.string().nullable()).nullable().optional(), planning_period: z.object({ days: z.array(z.string().min(1)).min(1).max(31) }).strict().nullable().optional(), scenario: scenario.nullable().optional(), budget: z.number().nonnegative().nullable().optional(), max_working_capacity_per_team: z.number().nonnegative().nullable().optional(), provenance: z.object({ source: z.string().min(1), imported_at: z.string().nullable().optional(), mapping_version: z.string().nullable().optional() }).strict().nullable().optional(), marginal_team_capacity: z.number().positive().default(16), target_priority_coverage: z.number().min(0).max(1).default(0.9) }).strict();

type Input = z.infer<typeof resourceAllocationRequestSchema>;
export type UiLocale = "uk" | "en" | "pl";
type Baseline = { metrics: Record<string, number>; summary: Record<string, number> };
const metricLabels: Record<UiLocale, Record<string, string>> = { uk: { priority_coverage: "покриття пріоритетних потреб", weighted_coverage: "зважене покриття потреб", total_coverage: "загальне покриття потреб", unmet_need: "непокриті потреби", capacity_utilization: "завантаження команд", travel_cost: "вартість переміщень", operating_cost: "операційна вартість", opening: "потреб на початку дня", served: "покрито потреб", closing_unmet: "залишилося без покриття" }, en: { priority_coverage: "priority coverage", weighted_coverage: "weighted coverage", total_coverage: "total coverage", unmet_need: "unmet need", capacity_utilization: "team utilization", travel_cost: "movement cost", operating_cost: "operating cost", opening: "opening needs", served: "needs served", closing_unmet: "needs left uncovered" }, pl: { priority_coverage: "pokrycie potrzeb priorytetowych", weighted_coverage: "ważone pokrycie potrzeb", total_coverage: "łączne pokrycie potrzeb", unmet_need: "niepokryte potrzeby", capacity_utilization: "wykorzystanie zespołów", travel_cost: "koszt przemieszczeń", operating_cost: "koszt operacyjny", opening: "potrzeby na początku dnia", served: "obsłużone potrzeby", closing_unmet: "potrzeby bez pokrycia" } };

function evidenceText(value: unknown, locale: UiLocale): string { if (typeof value === "string") return value; if (!value || typeof value !== "object") return String(value ?? ""); const item=value as Record<string,unknown>; const day=typeof item.day === "string" ? `${item.day}: ` : ""; const metricKey=typeof item.metric === "string" ? item.metric : "evidence"; const metric=metricLabels[locale][metricKey] ?? metricKey.replaceAll("_"," "); const raw=item.value; const percentage=["priority_coverage","weighted_coverage","total_coverage","capacity_utilization"].includes(metricKey) && typeof raw === "number"; const metricValue=percentage ? ` = ${Math.round((raw as number)*100)}%` : typeof raw === "number" || typeof raw === "string" ? ` = ${raw}` : ""; return `${day}${metric}${metricValue}`; }
function visibleOutcomeKey(value: unknown): string { if(!value || typeof value!=="object" || Array.isArray(value)) return "invalid"; const plan=value as Record<string,unknown>; const metrics=plan.aggregate_metrics && typeof plan.aggregate_metrics==="object" ? plan.aggregate_metrics as Record<string,unknown> : {}; const summary=plan.demand_summary && typeof plan.demand_summary==="object" ? plan.demand_summary as Record<string,unknown> : {}; const coverage=typeof metrics.priority_coverage==="number" ? Math.round(metrics.priority_coverage*100) : "na"; return `${coverage}|${String(summary.served??"na")}|${String(summary.closing_unmet??"na")}`; }
function normalizeResult(value: unknown, locale: UiLocale): unknown { if(!value || typeof value!=="object" || Array.isArray(value)) return value; const result={...(value as Record<string,unknown>)}; if(Array.isArray(result.alternatives)){ const seen=new Set<string>(); result.alternatives=result.alternatives.filter(plan=>{const key=visibleOutcomeKey(plan); if(seen.has(key)) return false; seen.add(key); return true;}).slice(0,4); } if(Array.isArray(result.evidence)) result.evidence=result.evidence.map(item=>evidenceText(item,locale)); return result; }
function normalizeEvidence(payload: Record<string,unknown>, locale: UiLocale): Record<string,unknown> { const normalized={...payload}; if(normalized.operation==="simulate" && normalized.result) normalized.result=normalizeResult(normalized.result,locale); else Object.assign(normalized,normalizeResult(normalized,locale)); return normalized; }
function baselineFromEvaluation(value: unknown): Baseline|null { if(!value || typeof value!=="object" || Array.isArray(value)) return null; const payload=value as Record<string,unknown>; const candidate=payload.result && typeof payload.result==="object" ? payload.result as Record<string,unknown> : payload; if(candidate.status && candidate.status!=="ok") return null; const metrics=candidate.aggregate_metrics, summary=candidate.demand_summary; if(!metrics || typeof metrics!=="object" || !summary || typeof summary!=="object") return null; return {metrics:metrics as Record<string,number>,summary:summary as Record<string,number>}; }
function attachBaseline(output: Record<string,unknown>, baseline: Baseline|null): Record<string,unknown> { if(output.operation!=="simulate" || !output.result || typeof output.result!=="object") return output; return {...output,result:{...(output.result as Record<string,unknown>),baseline}}; }

async function evaluateCurrentAllocation(input: Input): Promise<Baseline|null> { if(input.operation!=="simulate" || !input.current_allocation) return null; const days=input.planning_period?.days ?? []; if(days.length===0) return null; const manual_allocation=Object.fromEntries(days.map(day=>[day,input.current_allocation])); try { const evaluation=await runDipPlugin("resource-allocation","humanitarian.resource-allocation.optimize",{...input,operation:"evaluate_manual",manual_allocation}); return baselineFromEvaluation(evaluation); } catch(error){ if(error instanceof DipApiError) return null; throw error; } }

export async function runResourceAllocation(input: Input, locale: UiLocale): Promise<Record<string,unknown>> { const output=await runDipPlugin("resource-allocation","humanitarian.resource-allocation.optimize",input) as Record<string,unknown>; const baseline=await evaluateCurrentAllocation(input); return normalizeEvidence(attachBaseline(output,baseline),locale); }
