"use client";

import { useEffect, useState } from "react";
import { Check, CircleAlert, Flag, Gauge, Save, X } from "lucide-react";

type CapacityGap = { target_priority_coverage?: number; gap_to_target?: number; target_status?: string; minimum_capacity_to_target?: { resource?: string; added_capacity?: number } | null; bottlenecks?: Array<{ service?: string; gap?: number; binding?: boolean }> };
type Lifecycle = { decisionId: string; status: string } | null;
type Props = { input: Record<string, unknown>; selected: Record<string, unknown>; manualSelected?: Record<string, unknown> | null; priorityCoverage: number; served: number; unmet: number };
async function post(path: string, body: Record<string, unknown>) { const response = await fetch(path, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? payload.detail ?? `Request failed (${response.status})`); return payload; }

export function ResourceAllocationDecisionPanel({ input, selected, manualSelected, priorityCoverage, served, unmet }: Props) {
  const [capacity, setCapacity] = useState<CapacityGap | null>(null); const [lifecycle, setLifecycle] = useState<Lifecycle>(null); const [reason, setReason] = useState(""); const [notes, setNotes] = useState(""); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { setLifecycle(null); setCapacity(null); setReason(""); setNotes(""); }, [input]);
  async function capacityGap() { setBusy("capacity"); setError(null); try { setCapacity(await post("/api/resource-allocation/capacity-gap", { ...input, target_priority_coverage: 0.9 })); } catch (e) { setError(e instanceof Error ? e.message : "Capacity analysis failed"); } finally { setBusy(null); } }
  async function persist() { setBusy("persist"); setError(null); try { const payload = await post("/api/resource-allocation/decisions", input); setLifecycle({ decisionId: payload.decision_id, status: payload.status }); } catch (e) { setError(e instanceof Error ? e.message : "Decision persistence failed"); } finally { setBusy(null); } }
  async function feedback(status: "accepted" | "modified" | "rejected") { if (!lifecycle) return; setBusy(status); setError(null); try { const body: Record<string, unknown> = { status }; if (status === "modified") { body.reason = reason || "Manager manually adjusted the weekly allocation in Observatory."; body.selected = manualSelected ?? selected; } if (status === "rejected") body.reason = reason || "Manager rejected the proposed allocation."; const payload = await post(`/api/resource-allocation/decisions/${encodeURIComponent(lifecycle.decisionId)}/feedback`, body); setLifecycle({ ...lifecycle, status: payload.status }); } catch (e) { setError(e instanceof Error ? e.message : "Decision update failed"); } finally { setBusy(null); } }
  async function outcome() { if (!lifecycle) return; setBusy("outcome"); setError(null); try { const payload = await post(`/api/resource-allocation/decisions/${encodeURIComponent(lifecycle.decisionId)}/outcomes`, { actual_allocation: manualSelected ?? selected, metrics: { priority_coverage: priorityCoverage, served, closing_unmet: unmet }, notes: notes || "Demo outcome recorded from Observatory." }); setLifecycle({ ...lifecycle, status: payload.status }); } catch (e) { setError(e instanceof Error ? e.message : "Outcome recording failed"); } finally { setBusy(null); } }
  return <div className="grid gap-5 xl:grid-cols-2"><section className="bg-[#191919] p-6 text-white"><div className="flex items-center justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-wider text-red-400">08 · CAPACITY GAP</div><h3 className="mt-2 text-xl font-black">What capacity would change the result?</h3></div><Gauge className="h-6 w-6"/></div><button disabled={Boolean(busy)} onClick={capacityGap} className="mt-5 border border-white/25 px-4 py-3 text-sm font-bold disabled:opacity-40">{busy === "capacity" ? "Analyzing…" : "Analyze 90% priority target"}</button>{capacity && <div className="mt-5 space-y-4 text-sm"><div className="grid grid-cols-2 gap-3"><div className="border border-white/15 p-3"><span className="text-white/50">Gap to target</span><b className="mt-1 block text-xl">{Math.round((capacity.gap_to_target ?? 0) * 100)} pp</b></div><div className="border border-white/15 p-3"><span className="text-white/50">Status</span><b className="mt-1 block text-xl">{capacity.target_status ?? "—"}</b></div></div>{capacity.minimum_capacity_to_target && <div className="border-l-2 border-red-400 pl-3">Minimum tested addition: <b>{capacity.minimum_capacity_to_target.added_capacity ?? "—"}</b> for <b>{capacity.minimum_capacity_to_target.resource ?? "service"}</b>.</div>}{capacity.bottlenecks?.filter((item) => item.binding).slice(0, 4).map((item, index) => <div key={`${item.service}-${index}`} className="flex justify-between border-t border-white/10 pt-2"><span>{item.service}</span><b>gap {item.gap ?? "—"}</b></div>)}</div>}</section>
  <section className="bg-white p-6"><div className="text-xs font-bold uppercase tracking-wider text-[#d5222a]">09 · HUMAN DECISION</div><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><h3 className="text-xl font-black">Plan → decision → outcome</h3>{lifecycle && <span className="border border-black/10 px-3 py-1 text-xs font-bold uppercase">{lifecycle.status}</span>}</div>{manualSelected && !lifecycle && <div className="mt-4 border-l-2 border-[#d5222a] pl-3 text-sm">A feasible manager-edited plan is staged for <b>Modify</b>.</div>}{!lifecycle ? <button disabled={Boolean(busy)} onClick={persist} className="mt-5 flex items-center gap-2 bg-[#191919] px-4 py-3 text-sm font-bold text-white disabled:opacity-40"><Save className="h-4 w-4"/>{busy === "persist" ? "Creating snapshot…" : "Create immutable decision snapshot"}</button> : <><div className="mt-4 text-xs text-black/45">Decision ID · {lifecycle.decisionId}</div>{lifecycle.status === "proposed" && <><textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Reason for modification or rejection" className="mt-4 min-h-20 w-full border border-black/15 p-3 text-sm"/><div className="mt-3 flex flex-wrap gap-2"><button onClick={() => feedback("accepted")} disabled={Boolean(busy)} className="flex items-center gap-2 bg-[#191919] px-4 py-3 text-sm font-bold text-white"><Check className="h-4 w-4"/>Accept DIP plan</button><button onClick={() => feedback("modified")} disabled={Boolean(busy)} className="border border-black/20 px-4 py-3 text-sm font-bold">{manualSelected ? "Approve manual modification" : "Use selected alternative"}</button><button onClick={() => feedback("rejected")} disabled={Boolean(busy)} className="flex items-center gap-2 border border-red-300 px-4 py-3 text-sm font-bold text-red-700"><X className="h-4 w-4"/>Reject</button></div></>}{["accepted", "modified", "rejected"].includes(lifecycle.status) && <><textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Actual outcome notes" className="mt-4 min-h-20 w-full border border-black/15 p-3 text-sm"/><button onClick={outcome} disabled={Boolean(busy)} className="mt-3 flex items-center gap-2 bg-[#d5222a] px-4 py-3 text-sm font-bold text-white"><Flag className="h-4 w-4"/>{busy === "outcome" ? "Recording…" : "Record actual outcome"}</button></>}{lifecycle.status === "completed" && <div className="mt-5 border-l-2 border-green-700 pl-3 text-sm"><b>Decision completed.</b><div className="text-black/50">Recommendation, manager action and actual outcome are linked in the lifecycle.</div></div>}</>}{error && <div className="mt-4 border border-red-200 bg-red-50 p-3 text-sm text-red-700"><CircleAlert className="mr-2 inline h-4 w-4"/>{error}</div>}</section></div>;
}
