"use client";

import { useMemo, useState } from "react";
import { ArrowRight, Check, CircleAlert, Play, RotateCcw, SlidersHorizontal, Users, X } from "lucide-react";
import type { Locale } from "@/lib/observatory-i18n";

const DEMO = {
  planning_period: { id: "synthetic-week-01", label: "Демонстраційний тиждень" },
  communities: [
    { id: "Громада А", region: "Схід · synthetic", accessible: true, max_teams: 2, demand: [{ service: "psychologist", units: 8, priority: "critical" as const }, { service: "social-worker", units: 5, priority: "high" as const }] },
    { id: "Громада Б", region: "Схід · synthetic", accessible: true, max_teams: 2, demand: [{ service: "legal", units: 6, priority: "high" as const }, { service: "social-worker", units: 4, priority: "normal" as const }] },
    { id: "Громада В", region: "Схід · synthetic", accessible: false, max_teams: 1, demand: [{ service: "psychologist", units: 5, priority: "high" as const }] },
  ],
  teams: [
    { id: "Команда 1", current_community: "Громада Б", skills: ["psychologist", "social-worker"], capacity: 10 },
    { id: "Команда 2", current_community: "Громада А", skills: ["legal", "social-worker"], capacity: 8 },
    { id: "Команда 3", current_community: "Громада Б", skills: ["psychologist"], capacity: 5, allowed_communities: ["Громада А", "Громада Б"] },
  ],
  travel_edges: [{ from: "Громада Б", to: "Громада А", cost: 4 }, { from: "Громада А", to: "Громада Б", cost: 4 }],
  current_allocation: { "Команда 1": "Громада Б", "Команда 2": "Громада А", "Команда 3": "Громада Б" }, synthetic: true,
};

type Metrics = { priority_coverage: number; total_coverage: number; unmet_need: number; capacity_utilization: number; travel_cost: number };
type Alternative = { assignments: Record<string, string | null>; score: number; metrics: Metrics; binding_constraints: string[]; evidence: string[] };
type Result = { status: string; recommended: Alternative; alternatives: Alternative[]; baseline: Alternative | null; delta_vs_baseline: Record<string, number> | null; evidence: string[]; uncertainty: string[]; engine_version: string };
type DecisionState = "accepted" | "modify" | "rejected" | null;
const pct=(v:number)=>`${Math.round(v*100)}%`;
const evidenceLabels:Record<Locale,Record<string,string>>={uk:{"priority coverage":"Покриття пріоритетних потреб","total coverage":"Загальне покриття потреб","capacity utilization":"Використання команд","travel cost":"Витрати на переміщення"},en:{"priority coverage":"Priority needs covered","total coverage":"Total needs covered","capacity utilization":"Team capacity used","travel cost":"Travel cost"},pl:{"priority coverage":"Pokrycie potrzeb priorytetowych","total coverage":"Łączne pokrycie potrzeb","capacity utilization":"Wykorzystanie zespołów","travel cost":"Koszt przejazdów"}};
function evidence(line:string,locale:Locale){const m=line.match(/^([^=]+)=(-?\d+(?:\.\d+)?)$/);if(!m)return line;const k=m[1].trim(),v=Number(m[2]),label=evidenceLabels[locale][k]??k;return ["priority coverage","total coverage","capacity utilization"].includes(k)?`${label}: ${pct(v)}`:`${label}: ${v.toFixed(0)}`;}

function ImpactChart({baseline,active}:{baseline:Metrics|null;active:Metrics}){const rows=[{label:"Пріоритетні потреби",before:(baseline?.priority_coverage??0)*100,after:active.priority_coverage*100},{label:"Загальне покриття",before:(baseline?.total_coverage??0)*100,after:active.total_coverage*100},{label:"Використання команд",before:(baseline?.capacity_utilization??0)*100,after:active.capacity_utilization*100}];return <div className="space-y-5">{rows.map(r=><div key={r.label}><div className="mb-2 flex justify-between text-xs"><b>{r.label}</b><span>{Math.round(r.before)}% → <b>{Math.round(r.after)}%</b></span></div><div className="relative h-3 overflow-hidden rounded-full bg-black/10"><div className="absolute inset-y-0 left-0 bg-black/20 transition-all duration-700" style={{width:`${Math.min(100,r.before)}%`}}/><div className="absolute inset-y-0 left-0 bg-[#d5222a] transition-all duration-700" style={{width:`${Math.min(100,r.after)}%`}}/></div></div>)}</div>}

export function ResourceAllocationWorkspace({locale}:{locale:Locale}){
 const [result,setResult]=useState<Result|null>(null),[selected,setSelected]=useState(0),[running,setRunning]=useState(false),[error,setError]=useState<string|null>(null),[decision,setDecision]=useState<DecisionState>(null),[edit,setEdit]=useState(false),[manual,setManual]=useState<Record<string,string|null>>({...DEMO.current_allocation}),[availableC,setAvailableC]=useState(true),[capacityBoost,setCapacityBoost]=useState(0);
 async function run(overrides?:Record<string,string|null>){setRunning(true);setError(null);try{const input={...DEMO,communities:DEMO.communities.map(c=>c.id==="Громада В"?{...c,accessible:availableC}:c),teams:DEMO.teams.map(t=>({...t,capacity:t.capacity+capacityBoost})),current_allocation:overrides??DEMO.current_allocation};const response=await fetch("/api/resource-allocation/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"DIP request failed");setResult(payload);setSelected(0);if(!overrides)setManual(payload.recommended.assignments);}catch(e){setError(e instanceof Error?e.message:"DIP request failed")}finally{setRunning(false)}}
 const active=result?.alternatives[selected]??result?.recommended;
 const changed=useMemo(()=>active?Object.entries(active.assignments).filter(([team,to])=>DEMO.current_allocation[team as keyof typeof DEMO.current_allocation]!==to).length:0,[active]);
 function reset(){setResult(null);setError(null);setDecision(null);setEdit(false);setManual({...DEMO.current_allocation});setAvailableC(false);setCapacityBoost(0)}
 function startModify(){if(active)setManual({...active.assignments});setEdit(true);setDecision("modify")}
 function applyManual(){void run(manual);setEdit(false)}
 return <main className="min-h-screen bg-[#f7f5f2] text-[#191919]"><div className="mx-auto max-w-[1500px] px-5 py-8 md:px-10 lg:py-12">
 <header className="border-b border-black/15 pb-7"><div className="flex flex-wrap justify-between gap-3"><div className="text-xs font-bold uppercase tracking-[.18em] text-[#d5222a]">DIP · Resource Allocation</div><div className="rounded-full border border-[#d5222a]/30 bg-white px-3 py-1 text-xs font-semibold text-[#b51e25]">Синтетичні демонстраційні дані</div></div><h1 className="mt-5 text-4xl font-black tracking-tight md:text-6xl">Центр розподілу мобільних команд</h1><p className="mt-4 max-w-3xl text-black/55">Порівнюйте поточний план, рекомендацію DIP та власний сценарій. Змінюйте доступність і ресурси та одразу перевіряйте наслідки.</p></header>
 <section className="grid gap-5 py-7 xl:grid-cols-[360px_1fr]"><aside className="space-y-4"><div className="bg-[#191919] p-6 text-white"><div className="flex justify-between"><h2 className="font-bold">01 · Сценарій</h2><button onClick={reset}><RotateCcw className="h-4 w-4"/></button></div><div className="mt-5 space-y-5"><label className="flex items-center justify-between gap-3 text-sm"><span>Громада В доступна</span><input type="checkbox" checked={availableC} onChange={e=>setAvailableC(e.target.checked)} className="h-5 w-5 accent-[#d5222a]"/></label><label className="block text-sm"><div className="flex justify-between"><span>Додаткова місткість команд</span><b>+{capacityBoost}</b></div><input type="range" min="0" max="5" value={capacityBoost} onChange={e=>setCapacityBoost(Number(e.target.value))} className="mt-3 w-full accent-[#d5222a]"/></label></div><button onClick={()=>run()} disabled={running} className="mt-6 flex w-full items-center justify-center gap-2 bg-[#d5222a] p-4 font-bold disabled:opacity-50"><Play className="h-4 w-4"/>{running?"Перерахунок…":"Розрахувати сценарій"}</button></div>
 <div className="bg-white p-6"><h2 className="font-bold">02 · Операційний стан</h2><div className="mt-4 space-y-3">{DEMO.communities.map(c=><div key={c.id} className="border-t border-black/10 pt-3"><div className="flex justify-between"><b>{c.id}</b><span className="text-xs text-black/45">{c.id==="Громада В"?(availableC?"доступна":"недоступна"):"доступна"}</span></div><div className="mt-1 text-xs text-black/50">{c.demand.reduce((s,d)=>s+d.units,0)} потреб · до {c.max_teams} команд</div></div>)}</div></div></aside>
 <div className="space-y-5">{error&&<div className="border border-red-200 bg-white p-4 text-red-700"><CircleAlert className="mr-2 inline h-4 w-4"/>{error}</div>}{!result&&<div className="flex min-h-[520px] items-center justify-center border border-dashed border-black/15 bg-white text-center"><div><SlidersHorizontal className="mx-auto h-10 w-10 text-[#d5222a]"/><h2 className="mt-4 text-2xl font-black">Змініть умови та запустіть сценарій</h2><p className="mt-2 text-black/45">DIP побудує допустимі альтернативи і покаже вплив кожної.</p></div></div>}
 {result&&active&&<><div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="bg-white p-6"><div className="flex items-start justify-between"><div><div className="text-xs font-bold uppercase tracking-wider text-[#d5222a]">03 · Карта рішення</div><h2 className="mt-2 text-2xl font-black">{changed} команд змінюють розміщення</h2></div><span className="text-xs text-black/35">{result.engine_version}</span></div><div className="mt-6 grid gap-3 md:grid-cols-3">{DEMO.communities.map(c=><div key={c.id} className={`min-h-40 border p-4 transition-all duration-500 ${c.id==="Громада В"&&!availableC?"border-dashed opacity-45":"border-black/10"}`}><b>{c.id}</b><div className="mt-1 text-xs text-black/45">{c.demand.reduce((s,d)=>s+d.units,0)} потреб</div><div className="mt-5 space-y-2">{Object.entries(active.assignments).filter(([,place])=>place===c.id).map(([team])=><div key={team} className="rounded-full bg-[#d5222a] px-3 py-2 text-xs font-bold text-white transition-all duration-700">{team}</div>)}</div></div>)}</div></div><div className="bg-white p-6"><div className="text-xs font-bold uppercase tracking-wider text-[#d5222a]">Вплив рішення</div><h3 className="mt-2 text-xl font-black">Поточний план → обраний</h3><div className="mt-7"><ImpactChart baseline={result.baseline?.metrics??null} active={active.metrics}/></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="bg-[#f7f5f2] p-3"><div className="text-xs text-black/45">Незакриті потреби</div><b className="text-xl">{active.metrics.unmet_need.toFixed(0)}</b></div><div className="bg-[#f7f5f2] p-3"><div className="text-xs text-black/45">Переміщення</div><b className="text-xl">{active.metrics.travel_cost.toFixed(0)}</b></div></div></div></div>
 <div className="grid gap-5 lg:grid-cols-2"><div className="bg-white p-6"><h3 className="text-xl font-black">04 · Альтернативи</h3><div className="mt-4 space-y-2">{result.alternatives.map((a,i)=><button key={i} onClick={()=>{setSelected(i);setDecision(null)}} className={`w-full border p-4 text-left transition ${selected===i?"border-[#d5222a] bg-red-50":"border-black/10 hover:border-black/30"}`}><div className="flex justify-between gap-3"><b>{i===0?"Рекомендація DIP":`Сценарій ${i+1}`}</b><span>{pct(a.metrics.priority_coverage)}</span></div><div className="mt-1 text-xs text-black/45">покриття {pct(a.metrics.total_coverage)} · незакрито {a.metrics.unmet_need.toFixed(0)}</div></button>)}</div></div><div className="bg-white p-6"><h3 className="text-xl font-black">05 · Чому це рішення?</h3><div className="mt-4 space-y-3">{active.evidence.map(line=><div key={line} className="flex gap-2 text-sm"><ArrowRight className="mt-1 h-4 w-4 shrink-0 text-[#d5222a]"/>{evidence(line,locale)}</div>)}</div></div></div>
 {edit&&<div className="border-2 border-[#d5222a] bg-white p-6"><div className="flex items-center justify-between"><div><div className="text-xs font-bold uppercase tracking-wider text-[#d5222a]">Ручний сценарій</div><h3 className="mt-1 text-xl font-black">Змініть розміщення команд</h3></div><button onClick={()=>setEdit(false)}><X className="h-5 w-5"/></button></div><div className="mt-5 grid gap-3 md:grid-cols-3">{DEMO.teams.map(team=><label key={team.id} className="border border-black/10 p-4"><b>{team.id}</b><select value={manual[team.id]??""} onChange={e=>setManual(v=>({...v,[team.id]:e.target.value||null}))} className="mt-3 w-full border border-black/15 bg-white p-2"><option value="">Резерв</option>{DEMO.communities.map(c=><option key={c.id} value={c.id} disabled={c.id==="Громада В"&&!availableC}>{c.id}</option>)}</select></label>)}</div><button onClick={applyManual} className="mt-5 bg-[#191919] px-5 py-3 font-bold text-white">Перевірити мій сценарій</button></div>}
 <div className="sticky bottom-4 flex flex-wrap items-center gap-3 border border-black/10 bg-white/95 p-4 shadow-xl backdrop-blur"><div className="mr-auto"><div className="text-xs font-bold uppercase tracking-wider text-black/40">Рішення менеджера</div><div className="text-sm">{decision==="accepted"?"Рекомендацію прийнято":decision==="rejected"?"Рекомендацію відхилено":decision==="modify"?"Редагування сценарію":"Оберіть дію"}</div></div><button onClick={()=>setDecision("rejected")} className="border px-4 py-3 font-semibold"><X className="mr-1 inline h-4 w-4"/>Відхилити</button><button onClick={startModify} className="border px-4 py-3 font-semibold"><SlidersHorizontal className="mr-1 inline h-4 w-4"/>Змінити</button><button onClick={()=>setDecision("accepted")} className="bg-[#d5222a] px-5 py-3 font-bold text-white"><Check className="mr-1 inline h-4 w-4"/>Прийняти</button></div></>}
 </div></section></div></main>;
}
